#!/usr/bin/env bash
# gate-controls.sh - exercise tests/coverage-gate.sh against the REAL tracefile.
#
# The gate's entry floor and its zero-instrumented-line rule were, until this
# run, only ever exercised by tests/test-verification-debt.sh, which builds
# *synthetic* trees. This harness re-tests the same rules on the tracefile the
# real instrumented build produced (tests/coverage-run/coverage-fork.info), so
# the control and the measurement differ only in the mutation applied here.
#
#   control 1  real tracefile vs the repo baseline        -> expect exit 1 (the
#              recorded run's own verdict; nothing is mutated)
#   control 2  real tracefile, a baseline re-anchored to it -> expect exit 0
#              (positive control: the gate is not failing for an environmental
#              reason - parsing, paths, lcov version)
#   control 3  control-2 baseline with one file raised 20 points -> expect exit 1
#              (inverted check: the gate can still fail a passing tracefile, so
#              control 2's green is not a rubber stamp)
#   control 4  real tracefile with src/gui/PinConnector.cpp rewritten to 0
#              instrumented lines -> expect the documented "unmeasured
#              ... baseline 0.00% but this run reports 0 instrumented lines"
#   control 5  real tracefile plus a zero-line record for a scope file absent
#              from the baseline (include/CrashReporter.h) -> expect the
#              documented "unmeasurable (0 instrumented lines, recorded as n/a)"
#              and NOT a below-floor failure for it
#
# Usage: bash tests/coverage-run/gate-controls.sh <repo-root> <repo-tracefile>
set -uo pipefail

ROOT="$(cd "${1:?repo root}" && pwd)"
TRACE="${2:?tracefile}"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT
PASS=0; FAIL=0
check() { # check <label> <expected-exit> <actual-exit>
	if [ "$2" = "$3" ]; then echo "  OK   $1 (exit $3)"; PASS=$((PASS+1));
	else echo "  FAIL $1 (expected exit $2, got $3)"; FAIL=$((FAIL+1)); fi
}

echo "=== control 1: real tracefile vs the repo baseline (--check) ==="
bash "$ROOT/tests/coverage-gate.sh" "$TRACE" --check > "$WORK/c1.log" 2>&1
c1=$?; check "recorded verdict" 1 "$c1"

echo "=== building the re-anchored baseline used by controls 2 and 3 ==="
python3 - "$TRACE" "$WORK/anchored.tsv" "$ROOT" <<'PY'
import os, sys
trace, out, root = sys.argv[1], sys.argv[2], os.path.abspath(sys.argv[3])
rec = {}; cur = None
for line in open(trace, encoding="utf-8"):
    line = line.rstrip("\n")
    if line.startswith("SF:"):
        cur = line[3:]
        if cur.startswith(root + os.sep): cur = cur[len(root) + 1:]
        rec.setdefault(cur, [0, 0])
    elif line.startswith("LF:") and cur: rec[cur][0] = int(line[3:])
    elif line.startswith("LH:") and cur: rec[cur][1] = int(line[3:])
    elif line == "end_of_record": cur = None
with open(out, "w", encoding="utf-8") as fh:
    fh.write("# re-anchored copy of the baseline, generated by gate-controls.sh\n")
    for p, (lf, lh) in sorted(rec.items()):
        fh.write(f"{p}\t{(100.0*lh/lf) if lf else 0.0:.2f}\n")
PY

echo "=== control 2: real tracefile vs the re-anchored baseline (--check) ==="
bash "$ROOT/tests/coverage-gate.sh" "$TRACE" "$WORK/anchored.tsv" --check > "$WORK/c2.log" 2>&1
c2=$?; check "gate passes a tracefile its baseline was built from" 0 "$c2"
grep -E "tracefile line coverage|PASS" "$WORK/c2.log" | sed 's/^/     /'

echo "=== control 3: the same baseline with one file raised 20 points ==="
python3 - "$WORK/anchored.tsv" "$WORK/raised.tsv" <<'PY'
import sys
src, dst = sys.argv[1], sys.argv[2]
out = []
for line in open(src, encoding="utf-8"):
    if line.startswith("#") or not line.strip():
        out.append(line); continue
    p, _, pct = line.rstrip("\n").partition("\t")
    if p == "include/AudioPorts.h":      # 56.65% in the measured run
        pct = f"{min(100.0, float(pct) + 20.0):.2f}"
    out.append(f"{p}\t{pct}\n")
open(dst, "w", encoding="utf-8").writelines(out)
PY
bash "$ROOT/tests/coverage-gate.sh" "$TRACE" "$WORK/raised.tsv" --check > "$WORK/c3.log" 2>&1
c3=$?; check "gate still fails a tracefile whose baseline was raised" 1 "$c3"
grep -E "REGRESSION" "$WORK/c3.log" | sed 's/^/     /'

echo "=== control 4: a scope file rewritten to zero instrumented lines ==="
python3 - "$TRACE" "$WORK/zero-one.info" "$ROOT/src/gui/PinConnector.cpp" <<'PY'
import sys
src, dst, path = sys.argv[1], sys.argv[2], sys.argv[3]
out = []; cur = None; drop = False; buf = []
for line in open(src, encoding="utf-8"):
    t = line.rstrip("\n")
    if t.startswith("SF:"):
        cur = t[3:]; buf = [line]; drop = (cur == path)
        if not drop: out.extend(buf)   # every other record is copied verbatim
        continue
    if cur is None:
        out.append(line); continue
    if drop:
        if t.startswith("DA:"): continue
        if t.startswith("LF:"): buf.append("LF:0\n"); continue
        if t.startswith("LH:"): buf.append("LH:0\n"); continue
        if t == "end_of_record":
            out.extend(buf); out.append(line); cur = None; drop = False; continue
        continue
    out.append(line)
open(dst, "w", encoding="utf-8").writelines(out)
PY
bash "$ROOT/tests/coverage-gate.sh" "$WORK/zero-one.info" --check > "$WORK/c4.log" 2>&1
c4=$?; check "gate reacts to a now-zero-instrumented baseline file" 1 "$c4"
echo "     documented line present: $(grep -c 'unmeasured  src/gui/PinConnector.cpp: baseline 0.00% but this run reports 0 instrumented lines' "$WORK/c4.log")"
grep -E "unmeasurable|unmeasured" "$WORK/c4.log" | sed 's/^/     /'

echo "=== control 5: a scope file absent from the baseline, zero instrumented lines ==="
cp "$TRACE" "$WORK/zero-new.info"
python3 - "$WORK/zero-new.info" "$ROOT/include/CrashReporter.h" <<'PY'
import sys
path = sys.argv[2]
open(sys.argv[1], "a", encoding="utf-8").write(
    f"SF:{path}\nLF:0\nLH:0\nend_of_record\n")
PY
bash "$ROOT/tests/coverage-gate.sh" "$WORK/zero-new.info" --check > "$WORK/c5.log" 2>&1
c5=$?; check "gate reacts to a zero-instrumented new scope file" 1 "$c5"
echo "     documented line present: $(grep -c 'new         include/CrashReporter.h: unmeasurable (0 instrumented lines, recorded as n/a)' "$WORK/c5.log")"
echo "     admitted below the floor: $(grep -c 'include/CrashReporter.h: 0.00%' "$WORK/c5.log")  (0 = not refused)"
grep -E "unmeasurable" "$WORK/c5.log" | sed 's/^/     /'

echo
echo "=== gate-controls summary: $PASS passed, $FAIL failed ==="
[ "$FAIL" -eq 0 ]
