[  0%] Built target zene_api_autogen_timestamp_deps
[  5%] Built target lua
[  5%] Built target ringbuffer
[  5%] Built target weakjack
[  5%] Built target zene_api_autogen
[ 11%] Built target zene_api
[ 11%] Built target lmmsobjs_autogen_timestamp_deps
[ 11%] Built target lmmsobjs_autogen
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsVcaMix.cpp.o
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsVcaEdit.cpp.o
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsVcaEditSet.cpp.o
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/TrackContainerFolders.cpp.o
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsUndo.cpp.o
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsTransportMap.cpp.o
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsPunch.cpp.o
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsRecording.cpp.o
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsRecordingRecovery.cpp.o
[ 11%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlRecordingSupport.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/AudioInputPath.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/AudioWideInputStage.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RetroAudioCapture.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsRecordingInput.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsRecordingRoutes.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsRecordingRetro.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsWarp.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsWarpEdit.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/GrooveTemplate.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/GroovePool.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlGrooveSupport.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsGroove.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsGrooveEdit.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsGroovePool.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlDeviceCatalogue.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlDeviceHosted.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlDeviceState.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlDeviceSupport.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlDeviceVst3.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlDeviceClap.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlChainPresetSupport.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsChain.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsChainEdit.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ChordVocabulary.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ChordTrack.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ChordDetect.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ChordProgression.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlChordSupport.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsChord.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsChordEdit.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsChordWrite.cpp.o
[ 16%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlEditSupport.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlModulationSupport.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlRackSupport.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsProjectArchive.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlProjectAssets.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlProjectAssetsRelink.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsProjectMmpzGit.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsController.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsControllerTemplates.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControllerSurface.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlServer.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlServerSocket.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlServerWin32.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlSession.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlStructuralSupport.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Controller.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControllerConnection.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/DataFile.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/DrumSynth.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Effect.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/EffectChain.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/EffectChainPatcher.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Engine.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/EnvelopeAndLfoParameters.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ExportDither.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ExportRenderSettings.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/fft_helpers.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Mixer.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/VcaGroup.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ImportFilter.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/InlineAutomation.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Instrument.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/InstrumentFunctions.cpp.o
[ 22%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/InstrumentPlayHandle.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/InstrumentSoundShaping.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/JournallingObject.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Keymap.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Ladspa2LMMS.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/LadspaControl.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/LatencyCompensation.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/LoudnessReport.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/LufsMeter.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MasteringChain.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MasteringJob.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MasteringReport.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/LadspaManager.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/LfoController.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/LinkedModelGroups.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/LocklessAllocator.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MeterModel.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Metronome.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MicroTimer.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Microtuner.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MidiLearn.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MidiClock.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MidiClockState.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MidiClockTracker.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/MixHelpers.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Model.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ModelVisitor.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/NamespaceRegistry.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Note.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/NotePlayHandle.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/NoteRandom.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/NoteTransform.cpp.o
[ 27%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Oscillator.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PatchWiring.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PathUtil.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PatternClip.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PatternStore.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PeakController.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PerfLog.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Piano.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PlayHandle.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Plugin.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PluginIssue.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PluginFactory.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PluginScanCache.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/PresetPreviewPlayHandle.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectJournal.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectJournalBounds.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectJournalStructural.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectRecovery.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RecordingJournal.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectIds.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectRenderer.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectRevisions.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectVersion.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RemotePlugin.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Rack.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RackMacros.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RackNodes.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RackZones.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RenderManager.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RetroMidiCapture.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RetroMidiCaptureSettings.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RetroMidiClipWriter.cpp.o
[ 33%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RingBuffer.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RoutingChainNodes.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RoutingGraph.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RoutingNode.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/RoutingNodes.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Sample.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SampleBuffer.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SampleClip.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SampleDecoder.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SamplePlayHandle.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SampleRecordHandle.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Scale.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ScriptApiVersion.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ScriptBindings.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ScriptCommandQueue.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ScriptConsole.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ScriptDawBindings.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ScriptDawEdit.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ScriptDawEffects.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ScriptEngine.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ScriptPackage.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/LmmsSemaphore.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SerializingObject.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Song.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/TempoMap.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SmfInterchange.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SmfInterchangeReader.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/DawProjectZip.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/DawProjectModel.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/DawProjectWrite.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/DawProjectRead.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/DawProjectReadTracks.cpp.o
[ 38%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/DawProjectSession.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/DocumentIndex.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectContainer.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ProjectContainerEntries.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ModulationLayer.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/TempoSyncKnobModel.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ThreadPool.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Timeline.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/TimePos.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/TakeLane.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ToolPlugin.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Track.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/TrackContainer.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/UnattendedRun.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/UpgradeExtendedNoteRange.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/UnclaimedElements.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Clip.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ValueBuffer.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/VstSyncController.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/StepRecorder.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioAlsa.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioDevice.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioFileDevice.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioFileMP3.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioFileOgg.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioFileFlac.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioFileWave.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioJack.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioOss.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioSndio.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioPortAudio.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioSoundIo.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioPulseAudio.cpp.o
[ 44%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioSampleRecorder.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/AudioSdl.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/MultiTrackRecorder.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/audio/TrackRecorder.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2Basics.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2ControlBase.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2Evbuf.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2Features.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2Ports.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2Proc.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2Manager.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2Options.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2SubPluginFeatures.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2UridCache.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2UridMap.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/lv2/Lv2Worker.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiAlsaRaw.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiAlsaSeq.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiClient.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiController.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiEventToByteSeq.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiJack.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiOss.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiSndio.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiApple.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiPort.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiReconnect.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MpeExpression.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/midi/MidiWinMM.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SessionClip.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SessionModel.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SessionScheduler.cpp.o
[ 50%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsSession.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsSessionLaunch.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/SessionFollow.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsSessionFollow.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsSessionRecord.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/ControlCommandsSessionRecordLand.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/Telemetry.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/core/TelemetryNetworkTransport.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/ActionGroup.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/AudioAlsaSetupWidget.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/AudioDeviceSetupWidget.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/AutomatableModelView.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/ControlLayout.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/ControllerDialog.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/ControllerRackView.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/ControllerView.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/Controls.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/EffectControlDialog.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/EffectRackView.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/EffectView.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/embed.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/FileBrowser.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/FileRevealer.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/FileSearchJob.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/FocusDesk.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/FocusDeskModules.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/FocusDeskPane.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/FocusDeskPlacement.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/GuiApplication.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/LadspaControlView.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/LfoControllerDialog.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/LinkedModelGroupViews.cpp.o
[ 55%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/LmmsPalette.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/LmmsStyle.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/Lv2ViewBase.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/MainApplication.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/MainWindow.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/MicrotunerConfig.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/MidiCCRackView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/MidiLearnGui.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/MidiSetupWidget.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/MixerChannelView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/MixerView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/ModelView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/PeakControllerDialog.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/PinConnector.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/PluginBrowser.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/ProjectNotes.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/RowTableView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/SampleTrackWindow.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/SampleThumbnail.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/SendButtonIndicator.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/SideBar.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/SideBarWidget.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/StringPairDrag.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/SubWindow.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/ToolPluginView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/clips/AutomationClipView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/clips/ClipView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/clips/MidiClipView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/clips/PatternClipView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/clips/SampleClipView.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/AutomationEditor.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/Editor.cpp.o
[ 61%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/PatternEditor.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/PianoRoll.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/PositionLine.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/Rubberband.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/SongEditor.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/StepRecorderWidget.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/TimeLineWidget.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/editors/TrackContainerView.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/EnvelopeAndLfoView.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/EnvelopeGraph.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/InstrumentFunctionViews.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/InstrumentMidiIOView.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/InstrumentTuningView.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/InstrumentSoundShapingView.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/InstrumentTrackWindow.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/InstrumentView.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/LfoGraph.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/instrument/PianoView.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/menus/MidiPortMenu.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/menus/RecentProjectsMenu.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/menus/TemplatesMenu.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/modals/AboutDialog.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/modals/ColorChooser.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/modals/ControllerConnectionDialog.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/modals/EffectSelectDialog.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/modals/ExportProjectDialog.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/modals/FileDialog.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/modals/RenameDialog.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/modals/SetupDialog.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/modals/VersionedSaveDialog.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/AutomationTrackView.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/FadeButton.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/InstrumentTrackView.cpp.o
[ 66%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/PatternTrackView.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/SampleTrackView.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/TrackContentWidget.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/TrackLabelButton.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/TrackOperationsWidget.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/TrackRenameLineEdit.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/TrackGrip.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/tracks/TrackView.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/AutomatableButton.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/AutomatableSlider.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/BarModelEditor.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/CPULoadWidget.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/CaptionMenu.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/ComboBox.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/Draggable.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/Fader.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/FloatModelEditorBase.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/Graph.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/GroupBox.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/Knob.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/LcdFloatSpinBox.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/LcdSpinBox.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/LcdWidget.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/LedCheckBox.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/LeftRightNav.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/MeterDialog.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/MixerChannelLcdSpinBox.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/NStateButton.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/Oscilloscope.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/PeakIndicator.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/PixmapButton.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/SimpleTextFloat.cpp.o
[ 72%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/TabBar.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/TabWidget.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/TempoSyncBarModelEditor.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/TempoSyncKnob.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/TextFloat.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/TimeDisplayWidget.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/widgets/ToolButton.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/gui/TelemetryConsentDialog.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/AutomationTrack.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/InstrumentTrack.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/MidiClip.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/PatternTrack.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/SampleTrack.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/tracks/TrackFolder.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/common/RemotePluginBase.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/common/SharedMemory.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/common/SystemSemaphore.cpp.o
[ 77%] Building CXX object src/CMakeFiles/lmmsobjs.dir/qrc_lmms.cpp.o
[100%] Built target lmmsobjs
[100%] Built target DataFileSaveIntegrityTest_autogen_timestamp_deps
[100%] Automatic MOC for target DataFileSaveIntegrityTest
[100%] Built target DataFileSaveIntegrityTest_autogen
[100%] Building CXX object tests/CMakeFiles/DataFileSaveIntegrityTest.dir/DataFileSaveIntegrityTest_autogen/mocs_compilation.cpp.o
[100%] Building CXX object tests/CMakeFiles/DataFileSaveIntegrityTest.dir/src/core/DataFileSaveIntegrityTest.cpp.o
[100%] Linking CXX executable DataFileSaveIntegrityTest
[100%] Built target DataFileSaveIntegrityTest
