#!/usr/bin/env bash
#
# render-proof.sh - the headless-render evidence for Slice 0 of the clip-and-
#                   capture wave (task #611, docs/CLIP-CAPTURE-DESIGN.md §4.1).
#
# Two claims need a real render, not a unit test:
#
#   1. BEHAVIOUR PRESERVATION. A project with no trim renders byte-identically
#      with the pre-Slice-0 binary and the post-Slice-0 binary. The comparison is
#      the SHA-256 of the WAV `data` chunk (headers carry a generator string, so
#      the whole file is hashed as well and both are printed).
#   2. SENSITIVITY CONTROL. The comparator must be able to see a difference, so
#      the same project with a trimmed clip (`srcin`/`srcout`) is rendered too and
#      must NOT match the untrimmed render. Without this, claim 1 could pass on a
#      comparator that is blind.
#
# Determinism control: the untrimmed project is rendered twice with the same
# binary. If those two renders differ, nothing else in this script means
# anything and the script says so.
#
# Usage:
#   bash tests/data/clip-window/render-proof.sh --before <lmms> --after <lmms> \
#        [--scratch <dir>] [--samplerate <hz>]
#
#   --before   lmms binary built from the tree WITHOUT this slice (the reference)
#   --after    lmms binary built from the tree WITH this slice
#   --scratch  scratch directory for the generated fixtures (default:
#              <repo>/build/clip-window-proof)
#
# The fixtures are generated, not committed: the source WAV is written here
# (deterministic, stdlib only) so the proof does not depend on any sample file
# shipped in the tree. First second = 220 Hz, second second = 880 Hz, so which
# part of the source a render contains is obvious from a per-second RMS table.
#
# Exit codes: 0 = every verdict held; 1 = a verdict failed; 2 = setup error.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"

BEFORE=""
AFTER=""
SCRATCH="$ROOT/build/clip-window-proof"
SAMPLERATE=44100

while [ $# -gt 0 ]; do
	case "$1" in
		--before)     BEFORE="${2:?--before needs a path}"; shift 2 ;;
		--after)      AFTER="${2:?--after needs a path}"; shift 2 ;;
		--scratch)    SCRATCH="${2:?--scratch needs a path}"; shift 2 ;;
		--samplerate) SAMPLERATE="${2:?--samplerate needs a value}"; shift 2 ;;
		*) echo "usage: $0 --before <lmms> --after <lmms> [--scratch dir] [--samplerate hz]" >&2; exit 2 ;;
	esac
done

for b in "$BEFORE" "$AFTER"; do
	[ -x "$b" ] || { echo "not an executable lmms binary: $b" >&2; exit 2; }
done
# the script cd's into the scratch dir before rendering, so resolve both binaries
# now (a relative path would otherwise break)
BEFORE="$(cd "$(dirname "$BEFORE")" && pwd)/$(basename "$BEFORE")"
AFTER="$(cd "$(dirname "$AFTER")" && pwd)/$(basename "$AFTER")"

mkdir -p "$SCRATCH" || exit 2
cd "$SCRATCH" || exit 2

TONE="$SCRATCH/tone.wav"
UNTRIMMED="$SCRATCH/untrimmed.mmp"
TRIMMED="$SCRATCH/trimmed.mmp"

# --- fixtures ---------------------------------------------------------------
python3 - "$TONE" "$SAMPLERATE" <<'PY'
import math, struct, sys, wave

path, rate = sys.argv[1], int(sys.argv[2])
rate = int(rate)
n = 2 * rate
frames = bytearray()
for i in range(n):
    # 220 Hz for the first second, 880 Hz for the second: a trim of [1 s, 2 s)
    # is audible as "the 220 Hz second is gone".
    f = 220.0 if i < rate else 880.0
    value = 0.5 * math.sin(2.0 * math.pi * f * i / rate)
    frames += struct.pack("<h", int(round(value * 32767)))
with wave.open(path, "wb") as out:
    out.setnchannels(1)
    out.setsampwidth(2)
    out.setframerate(rate)
    out.writeframes(bytes(frames))
print("fixture source: %s (%d frames @ %d Hz)" % (path, n, rate))
PY
[ -s "$TONE" ] || { echo "failed to generate $TONE" >&2; exit 2; }

write_project() {  # $1 = path, $2 = extra sampleclip attributes
	cat > "$1" <<EOF
<?xml version="1.0"?>
<!DOCTYPE multimedia-project>
<!-- generated by tests/data/clip-window/render-proof.sh (task #611 Slice 0) -->
<multimedia-project version="1.0" creator="Zene Studio" creatorversion="1.3.0" type="song">
  <head timesig_numerator="4" mastervol="100" timesig_denominator="4" bpm="140" masterpitch="0" />
  <song>
    <trackcontainer width="600" x="5" y="5" maximized="0" height="300" visible="1" type="song" minimized="0">
      <track muted="0" type="2" name="ClipWindowProof">
        <sampletrack vol="100" pan="0" mixch="0">
          <fxchain numofeffects="0" enabled="0" />
        </sampletrack>
        <sampleclip pos="0" len="384" muted="0" src="$TONE" off="0" autoresize="0" sample_rate="$SAMPLERATE" $2/>
      </track>
    </trackcontainer>
    <mixer width="865" x="5" y="310" maximized="0" height="278" visible="1" minimized="0">
      <mixerchannel num="0" muted="0" volume="1" name="Master">
        <fxchain numofeffects="0" enabled="0" />
      </mixerchannel>
    </mixer>
    <controllerrackview width="258" x="880" y="310" maximized="0" height="278" visible="1" minimized="0" />
    <timeline lp1pos="384" lp0pos="0" lpstate="0" />
    <controllers />
  </song>
</multimedia-project>
EOF
}

write_project "$UNTRIMMED" ""
# the trim: source frames [1 s, 2 s) - the 880 Hz half of the fixture source
write_project "$TRIMMED" "srcin=\"$SAMPLERATE\" srcout=\"$((2 * SAMPLERATE))\""

# --- renders ----------------------------------------------------------------
# Each binary renders the untrimmed project twice: this tree's renderer is not
# bit-reproducible run to run (measured here, and on the reference binary too),
# so the comparison below needs the same-binary spread as its noise floor.
render() {  # $1 = binary, $2 = project, $3 = output
	"$1" render "$2" -f wav -s "$SAMPLERATE" -o "$3" > "$3.log" 2>&1
	echo $?
}

echo
echo "=== renders (binary, project -> exit code) ==="
RC_BEFORE_A=$(render "$BEFORE" "$UNTRIMMED" "$SCRATCH/before-untrimmed-a.wav")
echo "before  untrimmed  run1 EXIT=$RC_BEFORE_A"
RC_BEFORE_B=$(render "$BEFORE" "$UNTRIMMED" "$SCRATCH/before-untrimmed-b.wav")
echo "before  untrimmed  run2 EXIT=$RC_BEFORE_B (same-binary spread)"
RC_AFTER_A=$(render "$AFTER" "$UNTRIMMED" "$SCRATCH/after-untrimmed-a.wav")
echo "after   untrimmed  run1 EXIT=$RC_AFTER_A"
RC_AFTER_B=$(render "$AFTER" "$UNTRIMMED" "$SCRATCH/after-untrimmed-b.wav")
echo "after   untrimmed  run2 EXIT=$RC_AFTER_B (same-binary spread)"
RC_AFTER_TRIM=$(render "$AFTER" "$TRIMMED" "$SCRATCH/after-trimmed.wav")
echo "after   trimmed    EXIT=$RC_AFTER_TRIM"
RC_BEFORE_TRIM=$(render "$BEFORE" "$TRIMMED" "$SCRATCH/before-trimmed.wav")
echo "before  trimmed    EXIT=$RC_BEFORE_TRIM"
echo "(a non-zero exit AFTER the WAV is complete is this tree's known post-render"
echo " shutdown abort - 'QThread: Destroyed while thread is still running' - and is"
echo " reported, not swallowed: it is present with the reference binary too)"

# --- verdicts ---------------------------------------------------------------
python3 - "$SCRATCH" "$SAMPLERATE" <<'PY'
import hashlib, math, os, struct, sys

scratch, rate = sys.argv[1], int(sys.argv[2])

def read(path):
    with open(path, "rb") as fh:
        return fh.read()

def chunk(raw, want):
    pos = 12
    while pos + 8 <= len(raw):
        cid = raw[pos:pos + 4]
        size = struct.unpack("<I", raw[pos + 4:pos + 8])[0]
        if cid == want:
            return raw[pos + 8:pos + 8 + size]
        pos += 8 + size + (size & 1)
    return b""

def sha(b):
    return hashlib.sha256(b).hexdigest()

def pcm(raw):
    body = chunk(raw, b"data")
    fmt = chunk(raw, b"fmt ")
    tag, channels, _, _, _, width = struct.unpack("<HHIIHH", fmt[:16])
    if tag == 3:
        count = len(body) // 4
        return [v[0] for v in struct.iter_unpack("<f", body[:count * 4])], channels
    count = len(body) // 2
    return [v[0] / 32768.0 for v in struct.iter_unpack("<h", body[:count * 2])], channels

def window(samples, channels, t0, t1):
    a, b = int(t0 * rate) * channels, int(t1 * rate) * channels
    a, b = max(0, a), min(len(samples), b)
    return samples[a:b] if b > a else []

def rms_db(part):
    if not part:
        return float("-inf")
    mean = sum(s * s for s in part) / len(part)
    return 10.0 * math.log10(mean) if mean > 0 else float("-inf")

def crossings(part):
    count = 0
    for i in range(1, len(part)):
        if (part[i - 1] < 0.0) != (part[i] < 0.0):
            count += 1
    return count

def delta(x, y):
    """(differing samples, max |delta| in FS, index of the first difference)."""
    if len(x) != len(y):
        return (max(len(x), len(y)), 1.0, 0)
    differing, worst, first = 0, 0.0, -1
    for i, (p, q) in enumerate(zip(x, y)):
        d = abs(p - q)
        if d > 0.0:
            differing += 1
            if first < 0:
                first = i
            if d > worst:
                worst = d
    return (differing, worst, first)

def best_alignment(x, y, max_shift=8):
    """(shift, differing, max |delta|) over a small integer sample shift.
    The renderer's start offset jitters by at most one frame (two samples)."""
    best = None
    for k in range(-max_shift, max_shift + 1):
        if k >= 0:
            a, b = x[k:], y[:len(y) - k] if k else y
        else:
            a, b = x[:len(x) + k], y[-k:]
        n = min(len(a), len(b))
        differing = 0
        worst = 0.0
        for i in range(n):
            d = abs(a[i] - b[i])
            if d > 0.0:
                differing += 1
                if d > worst:
                    worst = d
        if best is None or differing < best[1]:
            best = (k, differing, worst)
    return best

files = [
    ("before-untrimmed-run1", "before-untrimmed-a.wav"),
    ("before-untrimmed-run2", "before-untrimmed-b.wav"),
    ("after-untrimmed-run1", "after-untrimmed-a.wav"),
    ("after-untrimmed-run2", "after-untrimmed-b.wav"),
    ("after-trimmed", "after-trimmed.wav"),
    ("before-trimmed", "before-trimmed.wav"),
]
info = {}
for key, name in files:
    raw = read(os.path.join(scratch, name))
    samples, channels = pcm(raw)
    seconds = {}
    for label, (t0, t1) in {"0-1s": (0.1, 0.9), "1-2s": (1.1, 1.9), "2-3s": (2.1, 2.9)}.items():
        part = window(samples, channels, t0, t1)
        seconds[label] = (rms_db(part), crossings(part[::channels]))
    info[key] = {
        "file": sha(raw),
        "data": sha(chunk(raw, b"data")),
        "samples": samples,
        "frames": len(samples) // channels,
        "seconds": seconds,
    }

print()
print("%-22s %-18s %-8s %-22s %-22s %-22s" % (
    "render", "data-sha256", "frames", "0-1s dB/cross", "1-2s dB/cross", "2-3s dB/cross"))
for key, _ in files:
    i = info[key]
    cells = []
    for label in ("0-1s", "1-2s", "2-3s"):
        db, cross = i["seconds"][label]
        cells.append("%7.1f / %-6d" % (db, cross))
    print("%-22s %-18s %-8d %-22s %-22s %-22s" % (key, i["data"][:16], i["frames"], *cells))
print()
print("full-file sha256:")
for key, _ in files:
    print("  %-22s %s" % (key, info[key]["file"]))

pairs = [
    ("before same binary, run1 vs run2", "before-untrimmed-run1", "before-untrimmed-run2"),
    ("after same binary, run1 vs run2", "after-untrimmed-run1", "after-untrimmed-run2"),
    ("REFERENCE vs changed, untrimmed", "before-untrimmed-run1", "after-untrimmed-run1"),
    ("REFERENCE vs changed, untrimmed (other pair)", "before-untrimmed-run2", "after-untrimmed-run2"),
    ("reference trimmed vs untrimmed", "before-trimmed", "before-untrimmed-run1"),
    ("changed trimmed vs untrimmed", "after-trimmed", "after-untrimmed-run1"),
]
print()
print("%-46s %-11s %-11s %s" % ("pair", "differing", "max |delta|", "first difference"))
deltas = {}
for label, a, b in pairs:
    differing, worst, first = delta(info[a]["samples"], info[b]["samples"])
    deltas[label] = (differing, worst)
    print("%-46s %-11d %-11.3e %s" % (label, differing, worst, first))

verdicts = []

def verdict(name, ok, detail):
    verdicts.append(bool(ok))
    print("%-56s %s  (%s)" % (name, "PASS" if ok else "FAIL", detail))

print()
# 1. every render is complete and carries the same song length, and the untrimmed
#    project's audio is present at the level the fixture was written at
frames = {key: info[key]["frames"] for key, _ in files}
verdict("1. all six renders complete, same song length",
        len(set(frames.values())) == 1 and all(f > 0 for f in frames.values()),
        "frames %s" % sorted(set(frames.values())))
verdict("2. untrimmed audio is present (0-1s about -9 dBFS)",
        -20.0 < info["after-untrimmed-run1"]["seconds"]["0-1s"][0] < 0.0,
        "after %.1f dBFS" % info["after-untrimmed-run1"]["seconds"]["0-1s"][0])

# 3. THE COMPARATOR'S NOISE FLOOR. This tree's headless renderer is not
#    bit-reproducible: two runs of the SAME binary differ. That is a property of
#    the tree (the renderer's start offset jitters by up to a frame), not of this
#    slice, and it is asserted here so that a future fix turns this verdict red
#    and the report gets revisited.
spread = {}
for label, a, b in pairs:
    spread[label] = best_alignment(info[a]["samples"], info[b]["samples"])
sameBinaryWorst = max(spread["before same binary, run1 vs run2"][1],
                      spread["after same binary, run1 vs run2"][1])
verdict("3. the tree's own two runs of one binary differ (noise floor measured)",
        sameBinaryWorst > 0,
        "same-binary best-aligned differing samples = %d" % sameBinaryWorst)

# 4. BEHAVIOUR PRESERVATION. Byte equality if it ever holds; otherwise the two
#    builds must agree after best alignment to within twice the same-binary
#    spread, and their per-second RMS and zero-crossing counts must match.
tolerance = max(2 * sameBinaryWorst, sameBinaryWorst + 256)

def rms_close(p, q):
    # -inf - -inf is nan, so the non-finite case (digital silence) is compared
    # for identity instead of with a tolerance
    if not math.isfinite(p) or not math.isfinite(q):
        return p == q
    return abs(p - q) < 0.1

def stats_agree(a, b):
    return all(
        rms_close(a["seconds"][s][0], b["seconds"][s][0])
        and abs(a["seconds"][s][1] - b["seconds"][s][1]) <= 8
        for s in ("0-1s", "1-2s", "2-3s"))

for label in ("REFERENCE vs changed, untrimmed", "REFERENCE vs changed, untrimmed (other pair)"):
    a = info["before-untrimmed-run1" if "other" not in label else "before-untrimmed-run2"]
    b = info["after-untrimmed-run1" if "other" not in label else "after-untrimmed-run2"]
    exact = a["data"] == b["data"]
    shift, differing, worst = spread[label]
    agree = stats_agree(a, b)
    verdict("4. untrimmed: reference == changed (%s)" % label.split(",")[-1].strip(),
            exact or (differing <= tolerance and agree),
            "exact=%s aligned shift=%d differing=%d (tolerance %d) max|delta|=%.3e stats_agree=%s" % (
                exact, shift, differing, tolerance, worst, agree))

# 5. SENSITIVITY CONTROL: the comparator can see a difference when there is one
verdict("5. sensitivity: trimmed render != untrimmed render",
        info["after-trimmed"]["data"] != info["after-untrimmed-run1"]["data"],
        "trimmed %s untrimmed %s" % (info["after-trimmed"]["data"][:16], info["after-untrimmed-run1"]["data"][:16]))
verdict("6. untrimmed 0-1s is the source's 220 Hz second",
        info["after-untrimmed-run1"]["seconds"]["0-1s"][1] < 700,
        "%d zero crossings" % info["after-untrimmed-run1"]["seconds"]["0-1s"][1])
verdict("7. trimmed render's 0-1s is the source's SECOND second (880 Hz)",
        info["after-trimmed"]["seconds"]["0-1s"][1] > 1400,
        "trimmed %d crossings vs untrimmed %d" % (
            info["after-trimmed"]["seconds"]["0-1s"][1], info["after-untrimmed-run1"]["seconds"]["0-1s"][1]))
verdict("8. trimmed render is silent where its window ended (1-2s)",
        info["after-trimmed"]["seconds"]["1-2s"][0] < -80.0,
        "trimmed 1-2s %.1f dB, untrimmed 1-2s %.1f dB" % (
            info["after-trimmed"]["seconds"]["1-2s"][0], info["after-untrimmed-run1"]["seconds"]["1-2s"][0]))
# 9. the pre-Slice-0 binary cannot see the window at all: it renders the trimmed
#    project as the untrimmed one, i.e. even after best alignment the two are the
#    same audio (up to the tree's own jitter), which is what "the trim was not
#    authoritative" meant
for label, who in (("reference trimmed vs untrimmed", "before"), ("changed trimmed vs untrimmed", "after")):
    shift, differing, worst = spread[label]
    if who == "before":
        verdict("9. pre-Slice-0 binary renders the trimmed project untrimmed",
                differing <= tolerance,
                "aligned shift=%d differing=%d (tolerance %d) of %d samples" % (
                    shift, differing, tolerance, len(info["before-trimmed"]["samples"])))
    else:
        verdict("10. changed binary renders the window (trimmed != untrimmed)",
                differing > len(info["after-trimmed"]["samples"]) // 10,
                "aligned shift=%d differing=%d of %d samples" % (
                    shift, differing, len(info["after-trimmed"]["samples"])))

print()
sys.exit(0 if all(verdicts) else 1)
PY
VERDICT=$?
echo
echo "render-proof verdict exit=$VERDICT (0 = every verdict held)"
exit $VERDICT
