set(WANT_SESSION_VIEW OFF)
set(WANT_TELEMETRY ON)
set(LMMS_HAVE_ALSA TRUE)
set(ZENE_TELEMETRY_ENABLED 1)
get_cmake_property(_define_vars VARIABLES)
foreach (_define_var ${_define_vars})
    if(_define_var MATCHES "^WANT|LMMS_(HAVE|DEBUG)" )
        list(APPEND LMMS_BUILD_OPTIONS "${_define_var}")
    endif()
endforeach()
message(STATUS "MATCHED-AS-BUILD-OPTIONS: ${LMMS_BUILD_OPTIONS}")
message(STATUS "ZENE_TELEMETRY_ENABLED is a declared variable: ${ZENE_TELEMETRY_ENABLED}")
