#!/usr/bin/env bash
# run.sh -- exercise include/fenv.h for BOTH Darwin architectures, on Linux.
#
# WHY THIS EXISTS
# ---------------
# The macos-arm64 job of the v0.2.0-alpha tag died with six errors of the form
#
#   include/fenv.h:20:24: error: no member named '__control' in 'fenv_t'
#   include/fenv.h:24:10: error: no member named '__mxcsr' in 'fenv_t'
#
# because the polyfill for feenableexcept poked fenv_t.__control/__mxcsr, which
# exist only in Darwin's x86_64 fenv_t; on arm64 Darwin's fenv_t is
# { unsigned long long __fpsr; unsigned long long __fpcr; }. That is a hard
# compile error on a platform no machine here can build for, so this harness
# side-steps the platform: it supplies a synthetic Darwin <fenv.h> carrying the
# per-architecture typedefs, FE_* macros and __fpcr enum EXACTLY as Apple's
# macOS 11.3 SDK declares them, points this repository's include/ at it, and
# then compiles and RUNS the polyfill:
#
#   arm64-fixed    include/fenv.h, __arm64__ selected   -> must compile, exit 0
#   arm64-before   the pre-fix header (*)               -> must FAIL to compile
#                                                          naming __control
#   x86_64-fixed   include/fenv.h, __x86_64__ selected  -> must compile, exit 0
#   x86_64-before  the pre-fix header                   -> must compile, exit 0
#   x86-branch     the x86_64 function bodies, diffed   -> must be empty
#
# (*) generated by `git show post-alpha/integration:include/fenv.h` -- the
#     header as it stood before the fix, byte-identical to upstream
#     origin/master's copy (verified: `git diff origin/master -- include/fenv.h`
#     is empty at that commit). Not committed: it is the same file git already
#     holds.
#
# The synthetic headers and the two check translation units are generated by
# this script into ./out/gen/ rather than committed, so that tests/ carries no
# standalone translation units that nothing builds. Everything under ./out/ is
# disposable; the verdict is re-derived on every run and lands in run.log.
#
# WHAT THIS DOES NOT PROVE: that Apple's SDK declares what the synthetic header
# says (that is quoted from the SDK, see the header comments) and that the real
# FPCR bits behave as the simulated register file does. Those two are the CI
# run's business; the bit arithmetic and the arch guard are this script's.
#
# Exit 0 only when every expectation holds.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKTREE="$(cd "$HERE/../../.." && pwd)"
GEN="$HERE/out/gen"
mkdir -p "$GEN/darwin-arm64" "$GEN/darwin-x86_64" "$GEN/before-include"

CXX="${CXX:-g++}"
BASE_FLAGS=(-std=c++17 -Wall -Wextra)
failures=0

report() { # report <case> <expected> <actual> <ok>
	printf '%-16s %-40s %-22s %s\n' "$1" "$2" "$3" "$4"
	[[ "$4" == "ok" ]] || failures=$((failures + 1))
}

# --- the synthetic Darwin system headers (generated) -----------------------
cat > "$GEN/darwin-arm64/fenv.h" <<'SYNTH_ARM64_EOF'
/* SYNTHETIC Darwin arm64 <fenv.h> -- shape taken verbatim from Apple's
 * MacOSX11.3.sdk/usr/include/fenv.h (the `#elif defined __arm64__` section:
 * the fenv_t typedef, the FE_* macros, the rounding modes and the __fpcr
 * trap/mode enum are copied unchanged; the SDK's own text is kept beside this
 * file as macos-fenv-SDK11.3.h).  fegetenv/fesetenv are storage-backed here so
 * the polyfill can be RUN on a Linux box: on Darwin they read and write the
 * real FPSR/FPCR registers, but what include/fenv.h computes is a bit mask, and
 * that is what this harness exercises.
 *
 * Those two functions and the two storage objects are the ONLY part of this
 * header that is not the SDK's text. */
#ifndef SYNTHETIC_DARWIN_ARM64_FENV_H
#define SYNTHETIC_DARWIN_ARM64_FENV_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    unsigned long long      __fpsr;
    unsigned long long      __fpcr;
} fenv_t;

typedef unsigned short fexcept_t;

#define FE_INEXACT          0x0010
#define FE_UNDERFLOW        0x0008
#define FE_OVERFLOW         0x0004
#define FE_DIVBYZERO        0x0002
#define FE_INVALID          0x0001
/*  FE_FLUSHTOZERO
    An ARM-specific flag that is raised when a denormal is flushed to zero.
    This is also called the "input denormal exception"                        */
#define FE_FLUSHTOZERO      0x0080
#define FE_ALL_EXCEPT       0x009f

#define FE_TONEAREST        0x00000000
#define FE_UPWARD           0x00400000
#define FE_DOWNWARD         0x00800000
#define FE_TOWARDZERO       0x00C00000

/*  Masks for values that may be controlled in the FPCR.  Modifying any other
    bits invokes undefined behavior.                                          */
enum {
    __fpcr_trap_invalid   = 0x00000100,
    __fpcr_trap_divbyzero = 0x00000200,
    __fpcr_trap_overflow  = 0x00000400,
    __fpcr_trap_underflow = 0x00000800,
    __fpcr_trap_inexact   = 0x00001000,
    __fpcr_trap_denormal  = 0x00008000,
    __fpcr_flush_to_zero  = 0x01000000,
};

/*  Mask for the QC bit of the FPSR                                           */
enum { __fpsr_saturation  = 0x08000000 };

extern const fenv_t _FE_DFL_ENV;
#define FE_DFL_ENV &_FE_DFL_ENV

/* --- test scaffolding, not part of the SDK header ------------------------ */
extern fenv_t __synth_fenv_registers;

static inline int fegetenv(fenv_t *envp) { *envp = __synth_fenv_registers; return 0; }
static inline int fesetenv(const fenv_t *envp) { __synth_fenv_registers = *envp; return 0; }

#ifdef __cplusplus
}
#endif

#endif /* SYNTHETIC_DARWIN_ARM64_FENV_H */
SYNTH_ARM64_EOF

cat > "$GEN/darwin-x86_64/fenv.h" <<'SYNTH_X86_EOF'
/* SYNTHETIC Darwin x86_64 <fenv.h> -- the `#elif defined __i386__ || defined
 * __x86_64__` section of Apple's MacOSX11.3.sdk/usr/include/fenv.h, copied
 * verbatim (typedef, FE_* macros, rounding modes), plus the storage-backed
 * fegetenv/fesetenv scaffolding described in darwin-arm64/fenv.h. */
#ifndef SYNTHETIC_DARWIN_X86_64_FENV_H
#define SYNTHETIC_DARWIN_X86_64_FENV_H

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    unsigned short          __control;      /* x87 control word               */
    unsigned short          __status;       /* x87 status word                */
    unsigned int            __mxcsr;        /* SSE status/control register    */
    char                    __reserved[8];  /* Reserved for future expansion  */
} fenv_t;

typedef unsigned short fexcept_t;

#define FE_INEXACT          0x0020
#define FE_UNDERFLOW        0x0010
#define FE_OVERFLOW         0x0008
#define FE_DIVBYZERO        0x0004
#define FE_INVALID          0x0001
#define FE_DENORMALOPERAND  0x0002
#define FE_ALL_EXCEPT       0x003f

#define FE_TONEAREST        0x0000
#define FE_DOWNWARD         0x0400
#define FE_UPWARD           0x0800
#define FE_TOWARDZERO       0x0c00

extern const fenv_t _FE_DFL_ENV;
#define FE_DFL_ENV &_FE_DFL_ENV

/* --- test scaffolding, not part of the SDK header ------------------------ */
extern fenv_t __synth_fenv_registers;

static inline int fegetenv(fenv_t *envp) { *envp = __synth_fenv_registers; return 0; }
static inline int fesetenv(const fenv_t *envp) { __synth_fenv_registers = *envp; return 0; }

#ifdef __cplusplus
}
#endif

#endif /* SYNTHETIC_DARWIN_X86_64_FENV_H */
SYNTH_X86_EOF

# --- the two check translation units (generated) ---------------------------
cat > "$GEN/check-arm64.cpp" <<'CHECK_ARM64_EOF'
// check-arm64.cpp -- runs the arm64 branch of include/fenv.h against the
// synthetic Darwin arm64 <fenv.h> beside this file.
//
// No C library headers here on purpose: the arm64 case is compiled with
// -U__x86_64__ -nostdinc so that the ONLY fenv.h in the search path is this
// repo's, resolved through the real include/ directory. The exit code is 0 when
// every check passes, otherwise the number of the FIRST failing check (see the
// numbering in the comments).
#include <fenv.h>

fenv_t __synth_fenv_registers = {0, 0};
const fenv_t _FE_DFL_ENV = {0, 0};

static int first_failure = 0;
static void expect(bool ok, int id) { if (!ok && first_failure == 0) first_failure = id; }

int main()
{
	typedef unsigned long long u64;

	// 1: FE_ALL_EXCEPT << 8 is exactly the union of the SDK's FPCR trap bits --
	//    the identity the arm64 branch is built on.
	expect((u64)(FE_ALL_EXCEPT << 8) ==
		(u64)(__fpcr_trap_invalid | __fpcr_trap_divbyzero | __fpcr_trap_overflow |
		      __fpcr_trap_underflow | __fpcr_trap_inexact | __fpcr_trap_denormal), 1);

	// 2: feenableexcept returns the previous MASKED set -- every exception is
	//    masked while no FPCR trap-enable bit is set, so that is FE_ALL_EXCEPT.
	__synth_fenv_registers.__fpcr = 0;
	int prev = feenableexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW);
	expect(prev == (int)FE_ALL_EXCEPT, 2);

	// 3: ... and sets exactly those three trap bits, nothing else.
	expect(__synth_fenv_registers.__fpcr ==
		(u64)(__fpcr_trap_invalid | __fpcr_trap_divbyzero | __fpcr_trap_overflow), 3);

	// 4: fedisableexcept reports the previous masked set -- the three enabled
	//    exceptions are the only ones NOT masked, so 0x9f & ~0x07 == 0x98.
	prev = fedisableexcept(FE_OVERFLOW);
	expect(prev == 0x98, 4);

	// 5: ... and clears only the requested bit.
	expect(__synth_fenv_registers.__fpcr == (u64)(__fpcr_trap_invalid | __fpcr_trap_divbyzero), 5);

	// 6: FE_FLUSHTOZERO is the denormal trap-enable bit (0x0080 << 8 == 0x8000).
	feenableexcept(FE_FLUSHTOZERO);
	expect((__synth_fenv_registers.__fpcr & (u64)__fpcr_trap_denormal) != 0, 6);

	// 7: the flush-to-zero MODE bit is not a trap enable and must survive.
	__synth_fenv_registers.__fpcr |= (u64)__fpcr_flush_to_zero;
	feenableexcept(FE_INEXACT);
	fedisableexcept(FE_ALL_EXCEPT);
	expect((__synth_fenv_registers.__fpcr & (u64)__fpcr_flush_to_zero) != 0, 7);

	// 8: disabling all exceptions clears every trap-enable bit.
	expect((__synth_fenv_registers.__fpcr & (u64)(FE_ALL_EXCEPT << 8)) == 0, 8);

	// 9: enabling all of them sets every one (FE_ALL_EXCEPT covers the six).
	feenableexcept(FE_ALL_EXCEPT);
	expect((__synth_fenv_registers.__fpcr & (u64)(FE_ALL_EXCEPT << 8)) == (u64)(FE_ALL_EXCEPT << 8), 9);

	// 10: no bit outside the trap mask plus the FZ mode bit is ever written.
	expect((__synth_fenv_registers.__fpcr &
		~(u64)(FE_ALL_EXCEPT << 8) & ~(u64)__fpcr_flush_to_zero) == 0, 10);

	return first_failure;
}
CHECK_ARM64_EOF

cat > "$GEN/check-x86_64.cpp" <<'CHECK_X86_EOF'
// check-x86_64.cpp -- runs the x86_64 branch of include/fenv.h (textually the
// upstream one, unchanged) against the synthetic Darwin x86_64 <fenv.h> beside
// this file, to show the branch still behaves as upstream designed it while the
// arm64 branch was added.
// Exit code: 0 when every check passes, else the first failing check number.
#include <fenv.h>

fenv_t __synth_fenv_registers = {};
const fenv_t _FE_DFL_ENV = {};

static int first_failure = 0;
static void expect(bool ok, int id) { if (!ok && first_failure == 0) first_failure = id; }

int main()
{
	// The x86_64 defaults Darwin's FE_DFL_ENV carries: x87 control 0x037f (every
	// exception masked; 1 bit == masked), MXCSR 0x1f80 (the same masks << 7).
	__synth_fenv_registers.__control = 0x037f;
	__synth_fenv_registers.__status = 0x0000;
	__synth_fenv_registers.__mxcsr = 0x1f80;
	for (int i = 0; i < 8; ++i) __synth_fenv_registers.__reserved[i] = 0;

	// 1: the previous (masked) set is reported. The x87 control word is
	//    active-low -- every FE_ALL_EXCEPT bit is set in Darwin's default
	//    0x037f -- so the value is FE_ALL_EXCEPT, not the three being enabled.
	int prev = feenableexcept(FE_INVALID | FE_DIVBYZERO | FE_OVERFLOW);
	expect(prev == FE_ALL_EXCEPT, 1);

	// 2: unmasking clears the x87 control bits ...
	expect(__synth_fenv_registers.__control == 0x0372, 2);

	// 3: ... and the MXCSR copies seven places higher.
	expect(__synth_fenv_registers.__mxcsr == 0x1900, 3);

	// 4: fedisableexcept sets them again and reports the previous masked set.
	prev = fedisableexcept(FE_OVERFLOW);
	expect(prev == 0x32, 4);
	expect(__synth_fenv_registers.__control == 0x037a, 5);
	expect(__synth_fenv_registers.__mxcsr == 0x1d00, 6);

	// 7: the x87 status word and the reserved bytes are never written.
	expect(__synth_fenv_registers.__status == 0x0000, 7);
	for (int i = 0; i < 8; ++i) if (__synth_fenv_registers.__reserved[i] != 0) { expect(false, 8); break; }
	expect(true, 8);

	// 9: FE_ALL_EXCEPT is the x87 masked-set mask (0x3f), not the MXCSR one.
	expect(FE_ALL_EXCEPT == 0x003f, 9);

	return first_failure;
}
CHECK_X86_EOF

# --- the pre-fix header (generated from git) -------------------------------
git -C "$WORKTREE" show post-alpha/integration:include/fenv.h > "$GEN/before-include/fenv.h" \
	|| { echo "error: cannot extract the pre-fix include/fenv.h" >&2; exit 2; }
git -C "$WORKTREE" show origin/master:include/fenv.h | diff -q - "$GEN/before-include/fenv.h" > /dev/null \
	|| echo "note: the pre-fix copy is NOT byte-identical to origin/master:include/fenv.h"

FIXED="$WORKTREE/include"
BEFORE="$GEN/before-include"

# --- arm64: the fixed header ----------------------------------------------
# -U__x86_64__ is what makes the arch guard select the arm64 branch on an
# x86_64 host; -nostdinc keeps every other fenv.h out of the search path.
ARM_FLAGS=(-nostdinc -D__APPLE__ -D__MACH__ -D__arm64__ -U__x86_64__)

"$CXX" "${BASE_FLAGS[@]}" "${ARM_FLAGS[@]}" -I"$FIXED" -I"$GEN/darwin-arm64" \
	"$GEN/check-arm64.cpp" -o "$GEN/check-arm64-fixed" > "$GEN/arm64-fixed.compile.log" 2>&1
cc=$?
if [[ $cc -ne 0 ]]; then
	report arm64-fixed "compiles, all checks pass" "compile exit $cc" "FAIL: compile error"
else
	"$GEN/check-arm64-fixed"; rc=$?
	[[ $rc -eq 0 ]] && report arm64-fixed "compiles, all checks pass" "harness exit 0" "ok" \
		|| report arm64-fixed "compiles, all checks pass" "harness exit $rc (check $rc)" "FAIL"
fi

# --- arm64: the pre-fix header must fail exactly as CI did -----------------
"$CXX" "${BASE_FLAGS[@]}" "${ARM_FLAGS[@]}" -I"$BEFORE" -I"$GEN/darwin-arm64" \
	"$GEN/check-arm64.cpp" -o "$GEN/check-arm64-before" > "$GEN/arm64-before.compile.log" 2>&1
cc=$?
if [[ $cc -eq 0 ]]; then
	report arm64-before "fails: no member named __control" "compile exit 0" "FAIL: pre-fix header compiled"
elif grep -q "__control" "$GEN/arm64-before.compile.log"; then
	report arm64-before "fails: no member named __control" "compile exit $cc" "ok"
else
	report arm64-before "fails: no member named __control" "compile exit $cc, other error" "FAIL"
fi

# --- x86_64: both headers ------------------------------------------------
for which in fixed before; do
	inc="$FIXED"; [[ $which == before ]] && inc="$BEFORE"
	"$CXX" "${BASE_FLAGS[@]}" -D__APPLE__ -D__MACH__ -I"$inc" -I"$GEN/darwin-x86_64" \
		"$GEN/check-x86_64.cpp" -o "$GEN/check-x86_64-$which" > "$GEN/x86_64-$which.compile.log" 2>&1
	cc=$?
	if [[ $cc -ne 0 ]]; then
		report "x86_64-$which" "compiles, all checks pass" "compile exit $cc" "FAIL: compile error"
	else
		"$GEN/check-x86_64-$which"; rc=$?
		[[ $rc -eq 0 ]] && report "x86_64-$which" "compiles, all checks pass" "harness exit 0" "ok" \
			|| report "x86_64-$which" "compiles, all checks pass" "harness exit $rc (check $rc)" "FAIL"
	fi
done

# --- the x86_64 branch must be upstream's text, not a rewrite -------------
awk '/^inline int feenableexcept/{f=1} f{ if (/^#elif defined\(__arm64__\)/) exit; print }' \
	"$FIXED/fenv.h" > "$GEN/x86-branch-fixed.txt"
awk '/^inline int feenableexcept/{f=1} f{ if (/^#endif/) exit; print }' \
	"$BEFORE/fenv.h" > "$GEN/x86-branch-before.txt"
if diff -u "$GEN/x86-branch-before.txt" "$GEN/x86-branch-fixed.txt" > "$GEN/x86-branch.diff" 2>&1; then
	report x86-branch "identical to the pre-fix branch" "empty diff" "ok"
else
	report x86-branch "identical to the pre-fix branch" "differs" "FAIL: x86_64 branch changed"
fi

echo
if [[ $failures -eq 0 ]]; then
	echo "PASS: include/fenv.h handles both Darwin fenv_t layouts; x86_64 unchanged"
	exit 0
fi
echo "FAIL: $failures expectation(s) unmet"
exit 1
