/*
 * ProjectContainerEntries.cpp - the `.mmpz` v2 document-level pair: the deriver
 *                               (document -> container entries) and the
 *                               reassembler (container entries -> document).
 *                               ARCH-4 S2c part 2.
 *
 * Both CONTRACTS live on their declarations in ProjectContainer.h, where the
 * two decisions they settle belong: the entry-naming reconciliation (the
 * index's `entry` attribute is not this container's key) and the RAW
 * byte-identity round trip, chosen against the spec's own corrected canonical
 * oracle. The comments here explain the local shape of the code only.
 *
 * This is a NEW file rather than more of ProjectContainer.cpp on purpose: that
 * file's charter says it moves entries and does not parse, prune or reduce
 * (ProjectContainer.h), and this pair is the parsing half of the bridge - it
 * reuses DocumentIndex's measured scanner and ProjectContainer's naming rules
 * across their contracts instead of restating either.
 *
 * Copyright (c) 2026 Zene Studio contributors
 *
 * This file is part of LMMS - https://lmms.io
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program (see COPYING); if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301 USA.
 */

#include "ProjectContainer.h"

#include "DocumentIndex.h"
#include "XmlDepthGuard.h"

#include <QByteArray>
#include <QDomDocument>
#include <QDomElement>
#include <QHash>
#include <QString>
#include <QStringList>
#include <QVector>
#include <QXmlStreamReader>

#include <utility>
#include <vector>

namespace lmms
{

namespace projectcontainer
{

namespace
{

void setError( QString* error, const QString& message )
{
	if( error ) { *error = message; }
}

/*! Parse \a bytes as a project document and locate \a contentElementName as a
 *  child of the ROOT - `<song>` under `<lmms-project>` - which is what
 *  documentIndex() and reduceDocumentSections() both assume the sections live
 *  between. Navigation only: the bytes either exported function answers for
 *  are the bytes the caller passed in, never a re-render of this DOM (the
 *  per-process attribute-order seed that forced sectionDigest() canonical
 *  never gets a vote here, because QDomDocument::save() is not called). */
bool openDocument( const QByteArray& bytes, const QString& contentElementName,
	QDomDocument* document, QDomElement* root, QDomElement* content, QString* error )
{
	if( contentElementName.isEmpty() )
	{
		setError( error, QStringLiteral(
			"no content element name, so the document's sections cannot be located" ) );
		return false;
	}
	QString depthError;
	if( !projectXmlDepthWithinLimit( bytes, &depthError ) )
	{
		setError( error, depthError );
		return false;
	}
	if( !document->setContent( bytes ) )
	{
		setError( error, QStringLiteral(
			"the document is not well-formed XML, so its container entries cannot be "
			"derived from it" ) );
		return false;
	}
	*root = document->documentElement();
	*content = root->firstChildElement( contentElementName );
	if( content->isNull() )
	{
		setError( error, QStringLiteral( "the document carries no <%1> element, so it "
			"has no content to take sections from" ).arg( contentElementName ) );
		return false;
	}
	return true;
}

/*! Parse the `<z:index>` \a root carries and validate it for splitting:
 *  present; every declared `<z:section>` row nameable; at least one row; and
 *  every row's name fileable by sectionEntryName().
 *
 *  Fills \a index, \a entryNames - the container entry name of row i, which is
 *  the deriver's OUTPUT names and the reassembler's EXPECTED set, generated by
 *  the one rule so the two cannot disagree - and \a skipNames (row names, for
 *  the range scan; the reassembler passes a throwaway, because it scans
 *  nothing). Both out-params are required rather than optional: one contract
 *  for both callers, instead of a null case each has to remember.
 *
 *  The nameless-row check is the one place this function deliberately does NOT
 *  follow parseDocumentIndex(), which skips such a row by contract (see its
 *  declaration): a dropped row silently shifts every later row's POSITION, and
 *  the position is the container's key. Counting declared rows against
 *  surviving rows turns that silent shift into a refusal. */
bool validatedIndexRows( const QDomElement& root, DocumentIndex* index,
	QVector<QString>* entryNames, QStringList* skipNames, QString* error )
{
	*index = parseDocumentIndex( root );

	const QDomElement declared = root.firstChildElement( documentIndexNodeName() );
	if( declared.isNull() )
	{
		setError( error, QStringLiteral( "the document carries no <%1>, so no section is "
			"declared - refusing to derive entries a reader could not map back" )
			.arg( documentIndexNodeName() ) );
		return false;
	}

	int rowsDeclared = 0;
	for( QDomNode node = declared.firstChild(); !node.isNull(); node = node.nextSibling() )
	{
		if( !node.isElement() ) { continue; }
		if( node.nodeName() == documentIndexSectionNodeName() ) { ++rowsDeclared; }
	}
	if( rowsDeclared != index->sections.size() )
	{
		setError( error, QStringLiteral( "the %1 carries a %2 with no name; a section "
			"that cannot be named cannot be matched to its bytes, so the input is "
			"refused rather than guessed at" )
			.arg( documentIndexNodeName(), documentIndexSectionNodeName() ) );
		return false;
	}
	if( index->isEmpty() )
	{
		setError( error, QStringLiteral( "the %1 names no sections, so no container "
			"entries can be derived from it - a v1 file is the honest shape" )
			.arg( documentIndexNodeName() ) );
		return false;
	}

	entryNames->clear();
	skipNames->clear();
	for( const DocumentSection& section : index->sections )
	{
		const QString entryName = sectionEntryName( entryNames->size(), section.name );
		if( entryName.isEmpty() )
		{
			setError( error, QStringLiteral( "the section '%1' cannot be filed under a "
				"container entry name (see sectionEntryName()), so it is refused rather "
				"than written as an entry the container would lose" )
				.arg( section.name ) );
			return false;
		}
		entryNames->append( entryName );
		skipNames->append( section.name );
	}
	return true;
}

/*! The index and the scan must describe the SAME sequence: equal length, same
 *  names in the same order. Both claim document order - the index because
 *  documentIndex() walks children in order, the scan because it only walks
 *  forward - so anything else means the index was authored against a different
 *  document than the one being split, and pairing row i to range i would be a
 *  guess about which section each entry name points at. */
bool indexMatchesRanges( const SectionRanges& found, const DocumentIndex& index,
	const QString& contentElementName, QString* error )
{
	if( found.ranges.size() != index.sections.size() )
	{
		setError( error, QStringLiteral( "the index names %1 sections but the document "
			"carries %2 children of <%3> the index would remove - index and document "
			"disagree, so nothing is derived" )
			.arg( index.sections.size() ).arg( found.ranges.size() ).arg( contentElementName ) );
		return false;
	}
	for( int i = 0; i < found.names.size(); ++i )
	{
		if( found.names.at( i ) != index.sections.at( i ).name )
		{
			setError( error, QStringLiteral( "index row %1 names '%2' but the document's "
				"section at that position is '%3' - the pairing would be a guess, so "
				"nothing is derived" )
				.arg( i + 1 ).arg( index.sections.at( i ).name, found.names.at( i ) ) );
			return false;
		}
	}
	return true;
}

/*! Walk \a xml - already open over \a bytes - to the start tag of the FIRST
 *  element named \a contentElementName, and answer the offset just past that
 *  tag, or -1 with \a error set. Matching the first element of that name, at
 *  any depth, is scanSectionRanges()'s own rule - and the caller has already
 *  proved with the DOM that a root child of that name exists, so the two
 *  parsers agree on which element this is.
 *
 *  Two measured properties do the arithmetic, both recorded on
 *  reduceDocumentSections: characterOffset() at a StartElement sits just PAST
 *  the start tag (property 1), and a literal '<' cannot occur inside a start
 *  tag, so the tag's own '<' is recovered with lastIndexOf (property 2's
 *  measurement). The tag's '>' is found by scanning from that '<' - the same
 *  technique tests/src/core/DocumentSectionsTest.cpp's sliceOf() uses - rather
 *  than by trusting where the token boundary falls on a SELF-CLOSED tag, which
 *  nothing in this tree has measured. The byte before the '>' then settles
 *  emptiness directly: a self-closed content element has no interior to splice
 *  sections into, and answering with the bytes after it would file them
 *  OUTSIDE the element they belong to - so it is refused by that statement.
 *
 *  The reader is left ON the content element's start token on purpose: the
 *  next phase walks its interior from there, in the same reader. A second
 *  reader over just the interior slice cannot work - the slice's first tag is
 *  the content element's own CLOSE tag, which is not well-formed on its own
 *  and comes back from Qt as an Invalid token (measured: Qt 6.4.2). */
bool walkToContentStart( QXmlStreamReader& xml, const QByteArray& bytes,
	const QString& contentElementName, qint64* startTagEnd, QString* error )
{
	while( !xml.atEnd() )
	{
		const QXmlStreamReader::TokenType token = xml.readNext();

		if( token != QXmlStreamReader::StartElement ) { continue; }
		if( xml.qualifiedName().toString() != contentElementName ) { continue; }

		const qint64 afterTag = xml.characterOffset();
		const qint64 tagStart = bytes.lastIndexOf( '<', afterTag - 1 );
		const qint64 tagEnd = tagStart < 0 ? -1 : bytes.indexOf( '>', tagStart );
		if( tagEnd <= 0 || bytes.at( tagEnd - 1 ) == '/' )
		{
			setError( error, QStringLiteral( "the <%1> element is empty, so there "
				"is no interior to place sections into" )
				.arg( contentElementName ) );
			return false;
		}
		*startTagEnd = tagEnd + 1;
		return true;
	}

	setError( error, QStringLiteral(
		"the document could not be followed to its end, so <%1> could not be located" )
		.arg( contentElementName ) );
	return false;
}

/*! Continue \a xml - parked on the content element's start token - until its
 *  own end tag, accepting whitespace only: \a innerEnd receives that end tag's
 *  '<' offset in \a bytes.
 *
 *  The walk needs no depth counter: the reader already holds `<song>` open, so
 *  the first EndElement it reaches IS the content element's own, and any
 *  element inside would bring its own start tag - a token this walk refuses -
 *  before its end tag. And once the walk has seen only whitespace, the first
 *  '<' after the start tag IS that close tag's '<', so the splice point never
 *  depends on how characterOffset() positions an EndElement. Anything else - a
 *  comment, a processing instruction, a child the index did not name,
 *  non-whitespace text - is refused by that statement rather than spliced
 *  around: it is exactly what would make the round trip's byte identity a
 *  guess. */
bool walkContentInterior( QXmlStreamReader& xml, const QByteArray& bytes,
	qint64 startTagEnd, qint64* innerEnd, const QString& contentElementName,
	QString* error )
{
	while( !xml.atEnd() )
	{
		const QXmlStreamReader::TokenType token = xml.readNext();

		if( token == QXmlStreamReader::EndElement )
		{
			*innerEnd = bytes.indexOf( '<', startTagEnd );
			if( *innerEnd < startTagEnd ) { break; } // unreachable; falls to the refusal
			return true;
		}
		if( token == QXmlStreamReader::Characters && xml.isWhitespace() ) { continue; }

		setError( error, QStringLiteral( "the interior of <%1> is not whitespace-only, "
			"so the index does not describe every child of it and a byte-exact "
			"reassembly would be a guess" ).arg( contentElementName ) );
		return false;
	}

	setError( error, QStringLiteral(
		"the document could not be followed to its end, so <%1>'s interior could not "
		"be located" ).arg( contentElementName ) );
	return false;
}

/*! Both halves of the splice geometry: [*innerBegin, *innerEnd) is the content
 *  element's interior - the bytes strictly between its start tag and the '<' of
 *  its close tag. The deriver asks to prove that region is whitespace once the
 *  sections are out; the reassembler asks for the same offsets to splice them
 *  back into. One reader walks both halves so the two provers cannot disagree
 *  about where "inside the content element" is. */
bool locateContentInterior( const QByteArray& bytes, const QString& contentElementName,
	qint64* innerBegin, qint64* innerEnd, QString* error )
{
	QXmlStreamReader xml( bytes );
	xml.setNamespaceProcessing( false );

	qint64 startTagEnd = 0;
	if( !walkToContentStart( xml, bytes, contentElementName, &startTagEnd, error ) )
	{
		return false;
	}

	*innerBegin = startTagEnd;
	return walkContentInterior( xml, bytes, startTagEnd, innerEnd, contentElementName, error );
}

/*! Cut \a derived out of \a document: the skeleton first (the document minus
 *  the EXTENDED ranges), then one pair per index row, in index order.
 *
 *  The extension is the whole trick, and it is not decoration: each range is
 *  grown from the section element's end to the next '<', so a section's ENTRY
 *  carries the element AND the whitespace that followed it, while the cut
 *  removes that same pair of bytes together - leaving the skeleton with only
 *  each section's LEADING whitespace. The reassembler then concatenates the
 *  entries in index order before the close tag, and `section + trailing
 *  whitespace` in sequence is exactly the interior the document had: no
 *  separator is invented, and none can be doubled. */
bool cutEntries( const QByteArray& document, const SectionRanges& found,
	const QVector<QString>& entryNames,
	std::vector<std::pair<QString, QByteArray>>* derived, QString* error )
{
	QVector<QPair<qint64, qint64>> cut;
	cut.reserve( found.ranges.size() );
	for( int i = 0; i < found.ranges.size(); ++i )
	{
		const QPair<qint64, qint64>& range = found.ranges.at( i );
		const qint64 nextTag = document.indexOf( '<', range.first + range.second );

		// Unreachable for a document scanSectionRanges() followed to its end -
		// the content element's own close tag is always a '<' after the last
		// section - and refused anyway: a range we cannot bound is bytes we
		// cannot account for, and silence would splice them wrong.
		if( nextTag < 0 )
		{
			setError( error, QStringLiteral( "section %1 of the index cannot be bound: "
				"no '<' follows it, so its bytes cannot be cut without guessing" )
				.arg( i + 1 ) );
			return false;
		}
		cut.append( qMakePair( range.first, nextTag - range.first ) );
	}

	derived->clear();
	derived->push_back( { skeletonEntryName(), removeRanges( document, cut ) } );
	for( int i = 0; i < cut.size(); ++i )
	{
		derived->push_back( { entryNames.at( i ),
			document.mid( cut.at( i ).first, cut.at( i ).second ) } );
	}
	return true;
}

/*! Split \a entries into the skeleton and the section bodies, checking the
 *  names by the same two rules the writer enforces: a repeated name is refused
 *  rather than merged (the write side's own refusal, and for the same reason -
 *  one body for two index rows is a section silently lost), and an entry that
 *  is neither the skeleton nor one isSectionEntryName() accepts marks the list
 *  as not this container's - a foreign archive, or a name writeContainer would
 *  never have written. The skeleton is found BY NAME, wherever it sits: the
 *  caller's list is in central-directory order and this function does not
 *  assume the writer put the skeleton first. */
bool partitionEntries( const std::vector<std::pair<QString, QByteArray>>& entries,
	QByteArray* skeleton, QHash<QString, QByteArray>* bodies, QString* error )
{
	bool sawSkeleton = false;
	for( const std::pair<QString, QByteArray>& entry : entries )
	{
		if( entry.first == skeletonEntryName() )
		{
			if( sawSkeleton )
			{
				setError( error, QStringLiteral( "two entries share the name '%1', so "
					"which one is the document would be a guess" )
					.arg( skeletonEntryName() ) );
				return false;
			}
			*skeleton = entry.second;
			sawSkeleton = true;
			continue;
		}
		if( !isSectionEntryName( entry.first ) )
		{
			setError( error, QStringLiteral( "'%1' is neither the skeleton nor a section "
				"entry this container writes, so these are not a v2 project's entries" )
				.arg( entry.first ) );
			return false;
		}
		if( bodies->contains( entry.first ) )
		{
			setError( error, QStringLiteral( "two sections share the container entry "
				"name '%1', which would lose one of them" ).arg( entry.first ) );
			return false;
		}
		bodies->insert( entry.first, entry.second );
	}

	if( !sawSkeleton )
	{
		setError( error, QStringLiteral( "the entries carry no '%1', so there is no "
			"document skeleton to rebuild from" ).arg( skeletonEntryName() ) );
		return false;
	}
	return true;
}

/*! The bodies and the index's expected names must be the SAME SET, in both
 *  directions: an expected name with no body would rebuild the document with a
 *  hole in it, and a body no row expects would sit nowhere - refused rather
 *  than dropped, because a container entry the index does not name is content
 *  this reader has no place for and no authority to discard. */
bool entriesMatchIndex( const QHash<QString, QByteArray>& bodies,
	const QVector<QString>& entryNames, QString* error )
{
	for( const QString& entryName : entryNames )
	{
		if( !bodies.contains( entryName ) )
		{
			setError( error, QStringLiteral( "the index names the entry '%1' but the "
				"entries carry no such section, so the document would be rebuilt with "
				"a hole in it" ).arg( entryName ) );
			return false;
		}
	}
	for( auto it = bodies.constBegin(); it != bodies.constEnd(); ++it )
	{
		if( !entryNames.contains( it.key() ) )
		{
			setError( error, QStringLiteral( "the entry '%1' is not one the index names, "
				"so it would sit nowhere in the rebuilt document" ).arg( it.key() ) );
			return false;
		}
	}
	return true;
}

} // namespace


bool deriveContainerEntries( const QByteArray& document,
	const QString& contentElementName,
	std::vector<std::pair<QString, QByteArray>>* entries, QString* error )
{
	if( entries == nullptr )
	{
		setError( error, QStringLiteral( "no destination for the derived entries" ) );
		return false;
	}

	QDomDocument dom;
	QDomElement root;
	QDomElement content;
	if( !openDocument( document, contentElementName, &dom, &root, &content, error ) )
	{
		return false;
	}

	DocumentIndex index;
	QVector<QString> entryNames;
	QStringList skipNames;
	if( !validatedIndexRows( root, &index, &entryNames, &skipNames, error ) )
	{
		return false;
	}

	SectionRanges found;
	if( !scanSectionRanges( document, contentElementName, skipNames, found ) )
	{
		// The two refusals scanSectionRanges() names - a document it cannot
		// follow to its end, a begin offset it cannot recover - are the same
		// ones reduceDocumentSections() answers with unchanged bytes; here they
		// are answered with no entries at all.
		setError( error, QStringLiteral( "the document could not be scanned to its "
			"end, so its sections cannot be cut without guessing" ) );
		return false;
	}
	if( !indexMatchesRanges( found, index, contentElementName, error ) ) { return false; }

	std::vector<std::pair<QString, QByteArray>> derived;
	if( !cutEntries( document, found, entryNames, &derived, error ) ) { return false; }

	// The skeleton's interior must be whitespace-only now that the indexed
	// sections are out of it: anything still in there is a child the index did
	// not name (an element, a comment), and splicing the entries back before
	// the close tag would move the sections past it - so the refusal is what
	// keeps the byte-identity promise true rather than probable.
	qint64 innerBegin = 0;
	qint64 innerEnd = 0;
	if( !locateContentInterior( derived.at( 0 ).second, contentElementName,
		&innerBegin, &innerEnd, error ) )
	{
		return false;
	}

	*entries = std::move( derived );
	return true;
}


bool reassembleContainerDocument( const std::vector<std::pair<QString, QByteArray>>& entries,
	const QString& contentElementName, QByteArray* document, QString* error )
{
	if( document == nullptr )
	{
		setError( error, QStringLiteral( "no destination for the reassembled document" ) );
		return false;
	}
	if( entries.empty() )
	{
		setError( error, QStringLiteral( "the container's entries are empty, so there "
			"is nothing to reassemble" ) );
		return false;
	}

	QByteArray skeleton;
	QHash<QString, QByteArray> bodies;
	if( !partitionEntries( entries, &skeleton, &bodies, error ) ) { return false; }

	QDomDocument dom;
	QDomElement root;
	QDomElement content;
	if( !openDocument( skeleton, contentElementName, &dom, &root, &content, error ) )
	{
		return false;
	}

	DocumentIndex index;
	QVector<QString> entryNames;
	QStringList scanNames; // a throwaway: the reassembler scans nothing
	if( !validatedIndexRows( root, &index, &entryNames, &scanNames, error ) ) { return false; }
	if( !entriesMatchIndex( bodies, entryNames, error ) ) { return false; }

	qint64 innerBegin = 0;
	qint64 innerEnd = 0;
	if( !locateContentInterior( skeleton, contentElementName, &innerBegin, &innerEnd, error ) )
	{
		return false;
	}

	// The splice: the skeleton up to the close tag, then every section body in
	// INDEX order - each body looked up by its generated name, which is why the
	// incoming pair order was never consulted - then the close tag and the
	// rest. Raw bytes in, raw bytes out, nothing re-serialised (the guarantee
	// is written up on deriveContainerEntries in ProjectContainer.h).
	QByteArray rebuilt = skeleton.left( innerEnd );
	for( const QString& entryName : entryNames )
	{
		rebuilt.append( bodies.value( entryName ) );
	}
	rebuilt.append( skeleton.mid( innerEnd ) );

	*document = std::move( rebuilt );
	return true;
}

} // namespace projectcontainer

} // namespace lmms
