#!/usr/bin/env python3
"""Appendix A's generator: the live command catalogue of a built zene binary.

WHAT IT PRINTS. One markdown catalogue of the command registry a RUNNING instance
answers with - a provenance block (the binary, its sha256, `control.version`, the
`control.transactions` caps), then one section per command GROUP holding a table
of every id in it: the id, whether the command mutates, and its one-line
description - exactly the material `docs/CAPABILITIES-0.3.0.md` Appendix A
commits. Nothing here is read from the source tree: every row is the live
instance's own `control.commands_list` reply, so the appendix cannot drift from
the binary the release ships.

HOW IT DRIVES THE INSTANCE. Through the tree's ONE control-surface harness
(`tests/control_socket_harness.py`, imported in place): the real binary started
with `--control-socket <tmp>/zene.sock` under `QT_QPA_PLATFORM=offscreen`, in its
own scratch HOME/XDG directory, driven by an external AF_UNIX client, closed with
`control.quit` and reaped by explicit PID. A hang is a failure, never a wait: the
harness bounds every read.

Usage:
    python3 scripts/capabilities-dump.py [<zene-binary>]

The binary defaults to `<tree's parent>/build/zene` - the layout this program's
worktrees use (`<parent>/build/zene` beside `<parent>/w<lane>/`). Exit codes:
0 = catalogue printed; 1 = the instance did not answer (the app log is dumped by
the harness); 2 = no binary at the path.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent          # <tree>/scripts
ROOT = HERE.parent                              # the tree this script belongs to
sys.path.insert(0, str(ROOT / "tests"))

import control_socket_harness as H  # noqa: E402  (path set above)


def parse_args(argv):
    parser = argparse.ArgumentParser(description="Emit the live command catalogue as markdown.")
    parser.add_argument("binary", nargs="?", default=None,
                        help="the built zene binary; defaults to <tree's parent>/build/zene")
    return parser.parse_args(argv[1:])


def resolve_binary(given):
    """The binary to measure, as (absolute path, None) or (None, why it cannot be used)."""
    path = os.path.abspath(given) if given else str(ROOT.parent / "build" / "zene")
    if not os.path.exists(path):
        return None, ("no binary at %s - pass one explicitly, or build this tree's parent "
                      "layout (<parent>/build/zene)" % path)
    return path, None


def sha256_of(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def one_line(text):
    """A description as one table cell: no newlines, no unescaped pipes."""
    return " ".join(str(text or "").replace("|", "\\|").split())


def call(client, request_id, cmd, expected=None):
    """One ok reply's `result`, or a hard stop naming the reply (a failure is never a skip)."""
    reply = client.call(request_id, cmd)
    if reply.get("id") != request_id:
        raise AssertionError("reply id %r != %r" % (reply.get("id"), request_id))
    if reply.get("ok") is not True:
        raise AssertionError("%s did not answer ok: %r" % (cmd, reply))
    return reply.get("result") or {}


def collect(instance, client):
    """The four reads this catalogue is made of, as one dict."""
    version = call(client, 1, "control.version")
    listing = call(client, 2, "control.commands_list")
    transactions = call(client, 3, "control.transactions")
    surface = call(client, 4, "control.surface_report")
    return {"version": version, "commands": listing.get("commands") or [],
            "count": listing.get("count"), "transactions": transactions, "surface": surface}


def groups_of(commands):
    """The commands grouped by their own `group` field, group and id order deterministic."""
    groups = {}
    for entry in commands:
        groups.setdefault(str(entry.get("group") or "ungrouped"), []).append(entry)
    return {name: sorted(entries, key=lambda item: str(item.get("id") or ""))
            for name, entries in sorted(groups.items())}


def provenance_markdown(binary, digest, facts):
    version = facts["version"]
    transactions = facts["transactions"]
    commands = facts["commands"]
    mutating = sum(1 for entry in commands if entry.get("mutating"))
    lines = [
        "<!-- Generated by scripts/capabilities-dump.py - do not edit by hand. Re-run it and "
        "replace this block, never hand-edit a row. -->",
        "",
        "| provenance | value |",
        "| --- | --- |",
        "| binary | `%s` |" % binary,
        "| binary sha256 | `%s` |" % digest,
        "| `control.version` | `%s` (proto %s) |" % (version.get("version"), version.get("proto")),
        "| surface | %d command ids in %d groups (%d mutating) |"
        % (len(commands), len(groups_of(commands)), mutating),
        "| `control.transactions` caps | records cap %s, bytes cap %s, retained %s bytes |"
        % (transactions.get("cap_records"), transactions.get("cap_bytes"),
           transactions.get("retained_bytes")),
        "| generated (UTC) | %s |"
        % datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ"),
    ]
    surface = facts["surface"]
    counts = surface.get("counts")
    if isinstance(counts, dict) and counts:
        lines.append("| `control.surface_report` counts | %s |"
                     % ", ".join("%s %s" % (key, counts[key]) for key in sorted(counts)))
    return lines


def catalogue_markdown(binary, digest, facts):
    lines = provenance_markdown(binary, digest, facts)
    for group, entries in groups_of(facts["commands"]).items():
        lines += ["", "### %s (%d ids)" % (group, len(entries)), "",
                  "| command | mutating | description |", "| --- | --- | --- |"]
        for entry in entries:
            lines.append("| `%s` | %s | %s |"
                         % (entry.get("id"), "yes" if entry.get("mutating") else "no",
                            one_line(entry.get("description"))))
    return "\n".join(lines) + "\n"


def main(argv):
    options = parse_args(argv)
    binary, why = resolve_binary(options.binary)
    if binary is None:
        print("cannot run: %s" % why, file=sys.stderr)
        return 2
    digest = sha256_of(binary)
    instance = H.start_instance(binary)
    try:
        client = H.connect(instance)
        H.wait_ready(instance, client, None)
        facts = collect(instance, client)
        if not facts["commands"]:
            raise AssertionError("control.commands_list answered with no commands array")
        print(catalogue_markdown(binary, digest, facts))
        call(client, 90, "control.quit")
        client.close()
        instance.wait_for_exit(H.QUIT_TIMEOUT)
        return 0
    except (H.Timeout, AssertionError) as error:
        H.fail("the catalogue could not be read from %s: %s" % (binary, error), instance)
    finally:
        instance.close()


if __name__ == "__main__":
    sys.exit(main(sys.argv))
