/*
 * ControlChordSupport.h - the helpers the chord.* command group shares between
 *                         its read half (ControlCommandsChord.cpp) and its edit
 *                         half (ControlCommandsChordEdit.cpp).
 *
 * The engine half is include/ChordTrack.h (the persistent track),
 * include/ChordDetect.h (what a clip's notes spell) and
 * include/ChordProgression.h (the catalogue and the seeded generator), all of
 * which are plain functions over plain data. What this file owns is the WIRE:
 * the JSON shapes, the argument readers, the two mechanisms a chord edit can be
 * reversed by, and the one note-writing call both generators use.
 *
 * Copyright (c) 2026 Zene Studio contributors
 *
 * This file is part of LMMS - https://lmms.io
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program (see COPYING); if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

#ifndef LMMS_CONTROL_CHORD_SUPPORT_H
#define LMMS_CONTROL_CHORD_SUPPORT_H

#include <vector>

#include <QJsonObject>
#include <QString>

#include "ChordDetect.h"
#include "ChordProgression.h"
#include "ChordTrack.h"
#include "ControlVocabulary.h" // the shared schema + id vocabulary
#include "lmms_export.h"

namespace lmms
{

class MidiClip;
struct ControlResult;

namespace control
{

//! Declared in ControlEdit.h; this header only passes references to it.
struct ClipRef;

//! The largest integer the schema subset can carry (the bound the groove and
//! warp groups state for the same reason: it is one wire, and a tick, a seed
//! and a length all travel on it).
constexpr int MaxSchemaInteger = 2147483647;

// ---------------------------------------------------------------------------
// The track
// ---------------------------------------------------------------------------

/*! The project's chord track, through the Song that owns it.
 *
 *  A chord track is project state, so it is addressed through the engine's own
 *  Song rather than a control-surface static: loading a project replaces it and
 *  a new project clears it. nullptr only before the engine exists, which every
 *  handler's engine check has already refused. */
ChordTrack* projectChordTrack();

//! The track's own XML, the before-state a recorded track edit restores.
QString chordTrackXml();

/*! Records the inverse of a track edit as an ACTION checkpoint
 *  (control::addUndoStep) and nothing else.
 *
 *  A chord track has no live object a journal checkpoint could restore: it is
 *  not in the track container and is not a JournallingObject, so a Song
 *  checkpoint does not carry it (the finding docs/GROOVE-POOL.md records for
 *  the pool and docs/TEMPO-MAP.md for the map). What is recorded is therefore
 *  the track's own serialized element, captured BEFORE the edit, written back
 *  by the step. \a before is that capture; the redo half captures the state as
 *  it is now, so a redo is faithful rather than a dropped step. */
void recordChordTrackRestore(const QString& before);

/*! The private "__transaction" payload of a track edit.
 *
 *  \a before is the track XML captured before the edit. The recorded inverse op
 *  is a named command the surface really implements (\a inverseOp with
 *  \a inverseArgs), so a reader can re-issue it by hand. */
QJsonObject chordTrackInverse(const QString& before, const QString& inverseOp,
	const QJsonObject& inverseArgs);

/*! The inverse payload of a CLIP edit: the clip's own journal checkpoint is
 *  the mechanism, so the recorded op is `control.undo` with the target as its
 *  argument. Deliberately NOT "the same command again": a generated take is not
 *  un-generated by generating it twice. */
QJsonObject chordClipInverse(const QJsonObject& before, const QJsonObject& target);

//! The mechanism text a track-editing verb records.
QString chordTrackMechanism();
//! The mechanism text a note-writing verb records (the clip's own checkpoint).
QString chordClipMechanism();

// ---------------------------------------------------------------------------
// The wire
// ---------------------------------------------------------------------------

//! One event as the wire reports it: position, length, root, octave, the
//! root's absolute key, the chord name and the scale name.
QJsonObject chordEventJson(const ChordEvent& event);

//! One event as the ARGUMENTS that write it back verbatim (chord.set's own
//! shape), so a recorded inverse is a call a reader can re-issue.
QJsonObject chordEventArgs(const ChordEvent& event);

//! The track half of every read-back this group returns.
QJsonObject chordTrackState(const ChordTrack& track);

//! chordTrackState()'s schema; \a extra adds the keys one command reports on
//! top of it.
QJsonObject chordTrackStateSchema(QJsonObject extra = QJsonObject());

//! The schema of one event object; the shape chord.get_state reports.
QJsonObject chordEventSchema();
//! The schema of chord.set's arguments (and of the recorded inverse).
QJsonObject chordEventArgsSchema();

//! The schema of the key estimate chord.detect reports.
QJsonObject chordKeySchema();

//! The schema of one progression the catalogue holds.
QJsonObject chordProgressionSchema();

//! The clip's own descriptor, taken BEFORE an edit (its id, its track and its
//! note count) - the before-state of a clip edit, bounded by construction.
QJsonObject chordClipBefore(const ClipRef& ref, const MidiClip& clip);

// ---------------------------------------------------------------------------
// Arguments
// ---------------------------------------------------------------------------

/*! Reads a chord event from \a args (pos and chord required, root, octave,
 *  length and scale optional) and proves it with ChordTrack::isWritable, so a
 *  name this engine cannot resolve is refused here rather than stored. */
bool readChordEvent(const QJsonObject& args, ChordEvent* out, ControlResult* error);

/*! Reads the detect options (window_ticks, min_pitch_classes), both optional. */
bool readDetectOptions(const QJsonObject& args, ChordDetect::DetectOptions* out, ControlResult* error);

/*! Reads a whole generation request: the progression, the key, the step, the
 *  pattern, the velocity and the seed. Every name is proved against the
 *  vocabulary here, so a caller that asks for a progression or a scale this
 *  engine does not have is told so, typed, before anything is written. */
bool readProgressionRequest(const QJsonObject& args, ChordProgression::Request* out,
	ControlResult* error);

// ---------------------------------------------------------------------------
// Writing notes
// ---------------------------------------------------------------------------

/*! Writes \a specs into \a clip and returns how many notes were added.
 *
 *  The clip must already be checkpointed by the caller (addJournalCheckPoint),
 *  and addNote's quantisation is OFF - the ticks a generator computed are the
 *  ticks it means (the rule note.add follows). */
int writeNoteSpecs(MidiClip* clip, const std::vector<ChordProgression::NoteSpec>& specs);

//! Removes every note from \a clip and returns how many there were.
int clearClipNotes(MidiClip* clip);

/*! The chords of a chord track as sounding keys, ready for
 *  ChordProgression::layOutChord: each event's chord entry, its tones above
 *  the root the event names. An event whose name no longer resolves is skipped
 *  (a track cannot hold one - ChordTrack::set refuses it - so this is a
 *  belt-and-braces read, not a branch a caller can reach). */
std::vector<int> eventKeys(const ChordEvent& event);

} // namespace control

} // namespace lmms

#endif // LMMS_CONTROL_CHORD_SUPPORT_H
