#!/usr/bin/env bash
#
# render-proof.sh - the headless-render evidence for task #597 (warp engine).
#
# Two claims need a real render, not a unit test:
#
#   1. BEHAVIOUR PRESERVATION. A project with no warp renders the same with the
#      pre-#597 binary and the #597 binary. This tree's renderer is NOT
#      bit-reproducible run to run (measured independently by the stem-export
#      lane, the clip-Slice-0 lane and the alpha baseline, and in stock LMMS
#      too), so the comparison is a sample delta against a run-to-run floor
#      MEASURED HERE on the same binary - never sha256 equality.
#   2. SENSITIVITY + A REAL MEASUREMENT. The same project with `<warp>` markers
#      must differ beyond that floor, and not merely "differ": a source whose
#      transients are at t = 0, 1, 2, 3 s must come out at t = 0, 0.5, 1.0, 1.5 s
#      - exactly 2x - because the marker pair declares 176400 source frames over
#      192 clip ticks where the project's own rate is 176400 over 384.
#
# Usage:
#   bash tests/data/warp/render-proof.sh --base <lmms> --warp <lmms> \
#        [--scratch <dir>] [--samplerate <hz>]
#
#   --base   lmms built from the tree BEFORE #597
#   --warp   lmms built from the tree WITH #597
#   --scratch  scratch dir (default <repo>/build/warp-proof)
#
# The fixtures are generated here (Python stdlib only), so the proof depends on
# no sample file shipped in the tree. Exit codes: 0 = every verdict held,
# 1 = a verdict failed, 2 = setup error.

set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/../../.." && pwd)"

BASE=""
WARP=""
SCRATCH="$ROOT/build/warp-proof"
SAMPLERATE=44100

while [ $# -gt 0 ]; do
	case "$1" in
		--base)       BASE="${2:?--base needs a path}"; shift 2 ;;
		--warp)       WARP="${2:?--warp needs a path}"; shift 2 ;;
		--scratch)    SCRATCH="${2:?--scratch needs a path}"; shift 2 ;;
		--samplerate) SAMPLERATE="${2:?--samplerate needs a value}"; shift 2 ;;
		*) echo "usage: $0 --base <lmms> --warp <lmms> [--scratch dir] [--samplerate hz]" >&2; exit 2 ;;
	esac
done

for b in "$BASE" "$WARP"; do
	[ -x "$b" ] || { echo "not an executable lmms binary: $b" >&2; exit 2; }
done
BASE="$(cd "$(dirname "$BASE")" && pwd)/$(basename "$BASE")"
WARP="$(cd "$(dirname "$WARP")" && pwd)/$(basename "$WARP")"

mkdir -p "$SCRATCH" || exit 2
cd "$SCRATCH" || exit 2

BURSTS="$SCRATCH/bursts.wav"
PLAIN="$SCRATCH/plain.mmp"
WARPED="$SCRATCH/warped.mmp"

# --- fixtures ---------------------------------------------------------------
# 4 s of 1 kHz bursts, 0.2 s long, at the start of each second. A transient's
# output position is therefore directly measurable, which is what makes
# "the clip plays at a different rate" a fact rather than "it changed".
python3 - "$BURSTS" "$SAMPLERATE" <<'PY'
import math, struct, sys, wave

path, rate = sys.argv[1], int(sys.argv[2])
rate = int(rate)
seconds = 4
burst = 0.2
frames = bytearray()
for i in range(seconds * rate):
    inside = (i % rate) < int(burst * rate)
    value = 0.5 * math.sin(2.0 * math.pi * 1000.0 * i / rate) if inside else 0.0
    frames += struct.pack("<h", int(round(value * 32767)))
with wave.open(path, "wb") as out:
    out.setnchannels(1)
    out.setsampwidth(2)
    out.setframerate(rate)
    out.writeframes(bytes(frames))
print("fixture source: %s (%d frames @ %d Hz, bursts at 0/1/2/3 s)" % (path, seconds * rate, rate))
PY
[ -s "$BURSTS" ] || { echo "failed to generate $BURSTS" >&2; exit 2; }

# 120 bpm, 4/4 -> 192 ticks per bar; the clip is 384 ticks = 2 bars = 4 s, which
# is the whole source at the project's own rate.
write_project() {  # $1 = path, $2 = extra XML inside the sampleclip
	cat > "$1" <<EOF
<?xml version="1.0"?>
<!DOCTYPE multimedia-project>
<!-- generated by tests/data/warp/render-proof.sh (task #597) -->
<multimedia-project version="1.0" creator="Zene Studio" creatorversion="1.3.0" type="song">
  <head timesig_numerator="4" mastervol="100" timesig_denominator="4" bpm="120" masterpitch="0" />
  <song>
    <trackcontainer width="600" x="5" y="5" maximized="0" height="300" visible="1" type="song" minimized="0">
      <track muted="0" type="2" name="WarpProof">
        <sampletrack vol="100" pan="0" mixch="0">
          <fxchain numofeffects="0" enabled="0" />
        </sampletrack>
        <sampleclip pos="0" len="384" muted="0" src="$BURSTS" off="0" autoresize="0" sample_rate="$SAMPLERATE">$2</sampleclip>
      </track>
    </trackcontainer>
    <mixer width="865" x="5" y="310" maximized="0" height="278" visible="1" minimized="0">
      <mixerchannel num="0" muted="0" volume="1" name="Master">
        <fxchain numofeffects="0" enabled="0" />
      </mixerchannel>
    </mixer>
    <controllerrackview width="258" x="880" y="310" maximized="0" height="278" visible="1" minimized="0" />
    <timeline lp1pos="384" lp0pos="0" lpstate="0" />
    <controllers />
  </song>
</multimedia-project>
EOF
}

write_project "$PLAIN" ""
# The warp: source frame 176400 (the whole 4 s) is pinned to clip tick 192
# instead of the 384 the project's own rate would put it at - a 2x rate. Marker
# 1 pins the source's first frame to the clip's own origin, which is also what
# the unwarped map says, so the two projects are identical except for the rate.
write_project "$WARPED" "
          <warp mode=\"follow\">
            <marker src=\"0\" pos=\"0\" />
            <marker src=\"176400\" pos=\"192\" />
          </warp>"

# --- renders ----------------------------------------------------------------
render() {  # $1 = binary, $2 = project, $3 = output
	"$1" render "$2" -f wav -s "$SAMPLERATE" -o "$3" > "$3.log" 2>&1
	echo $?
}

echo
echo "=== renders (binary, project -> exit code) ==="
RC_BASE_A=$(render "$BASE" "$PLAIN" "$SCRATCH/base-plain-a.wav")
echo "base plain  run1 EXIT=$RC_BASE_A"
RC_BASE_B=$(render "$BASE" "$PLAIN" "$SCRATCH/base-plain-b.wav")
echo "base plain  run2 EXIT=$RC_BASE_B (same-binary spread)"
RC_WARP_A=$(render "$WARP" "$PLAIN" "$SCRATCH/warp-plain-a.wav")
echo "warp plain  run1 EXIT=$RC_WARP_A"
RC_WARP_B=$(render "$WARP" "$PLAIN" "$SCRATCH/warp-plain-b.wav")
echo "warp plain  run2 EXIT=$RC_WARP_B (same-binary spread)"
RC_WARP_W=$(render "$WARP" "$WARPED" "$SCRATCH/warp-warped.wav")
echo "warp warped      EXIT=$RC_WARP_W"
RC_BASE_W=$(render "$BASE" "$WARPED" "$SCRATCH/base-warped.wav")
echo "base warped      EXIT=$RC_BASE_W"
echo "(a non-zero exit AFTER the WAV is complete is this tree's known post-render"
echo " shutdown abort - 'QThread: Destroyed while thread is still running' - and is"
echo " reported, not swallowed: it is present with the base binary too)"

# --- verdicts ---------------------------------------------------------------
python3 - "$SCRATCH" "$SAMPLERATE" <<'PY'
import hashlib, math, os, struct, sys

scratch, rate = sys.argv[1], int(sys.argv[2])

def read(path):
    with open(path, "rb") as fh:
        return fh.read()

def chunk(raw, want):
    pos = 12
    while pos + 8 <= len(raw):
        cid = raw[pos:pos + 4]
        size = struct.unpack("<I", raw[pos + 4:pos + 8])[0]
        if cid == want:
            return raw[pos + 8:pos + 8 + size]
        pos += 8 + size + (size & 1)
    return b""

def pcm(raw):
    body = chunk(raw, b"data")
    fmt = chunk(raw, b"fmt ")
    tag, channels, _, _, _, width = struct.unpack("<HHIIHH", fmt[:16])
    if tag == 3:
        count = len(body) // 4
        return [v[0] for v in struct.iter_unpack("<f", body[:count * 4])], channels
    count = len(body) // 2
    return [v[0] / 32768.0 for v in struct.iter_unpack("<h", body[:count * 2])], channels

def rms_db(part):
    if not part:
        return float("-inf")
    mean = sum(s * s for s in part) / len(part)
    return 10.0 * math.log10(mean) if mean > 0 else float("-inf")

def delta(x, y):
    if len(x) != len(y):
        return (max(len(x), len(y)), 1.0)
    differing, worst = 0, 0.0
    for p, q in zip(x, y):
        d = abs(p - q)
        if d > 0.0:
            differing += 1
            if d > worst:
                worst = d
    return (differing, worst)

def best_alignment(x, y, max_shift=8):
    """(shift, differing, max |delta|): the renderer's start offset jitters."""
    best = None
    for k in range(-max_shift, max_shift + 1):
        if k >= 0:
            a, b = x[k:], (y[:len(y) - k] if k else y)
        else:
            a, b = x[:len(x) + k], y[-k:]
        n = min(len(a), len(b))
        differing, worst = 0, 0.0
        for i in range(n):
            d = abs(a[i] - b[i])
            if d > 0.0:
                differing += 1
                if d > worst:
                    worst = d
        if best is None or differing < best[1]:
            best = (k, differing, worst)
    return best

def onset(samples, channels, t0, t1, threshold=0.2):
    """First sample above `threshold` in [t0, t1); None if the window is silent."""
    a, b = int(t0 * rate) * channels, int(t1 * rate) * channels
    a, b = max(0, a), min(len(samples), b)
    for i in range(a, b, channels):
        if abs(samples[i]) > threshold:
            return (i // channels) / float(rate)
    return None

def level(samples, channels, t0, t1):
    a, b = int(t0 * rate) * channels, int(t1 * rate) * channels
    a, b = max(0, a), min(len(samples), b)
    return rms_db(samples[a:b]) if b > a else float("-inf")

files = [
    ("base-plain-run1", "base-plain-a.wav"),
    ("base-plain-run2", "base-plain-b.wav"),
    ("warp-plain-run1", "warp-plain-a.wav"),
    ("warp-plain-run2", "warp-plain-b.wav"),
    ("warp-warped", "warp-warped.wav"),
    ("base-warped", "base-warped.wav"),
]
info = {}
for key, name in files:
    raw = read(os.path.join(scratch, name))
    samples, channels = pcm(raw)
    # the fixture's bursts are 0.2 s long; at 2x they are 0.1 s. Measuring
    # [onset + 15 ms, onset + 85 ms] catches either without touching a boundary.
    measured = {}
    for second in range(4):
        for candidate in (0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5):
            label = "%.2f" % candidate
            if label in measured:
                continue
            hit = onset(samples, channels, candidate, candidate + 0.12)
            if hit is not None:
                measured[label] = (hit, level(samples, channels, hit + 0.015, hit + 0.085))
    info[key] = {
        "file": hashlib.sha256(raw).hexdigest(),
        "samples": samples,
        "frames": len(samples) // channels,
        "onsets": measured,
        "tail": level(samples, channels, 2.05, 5.9),
    }

print()
print("%-18s %-18s %-8s %s" % ("render", "data-sha256", "frames", "measured burst onsets (s -> dBFS)"))
for key, _ in files:
    i = info[key]
    shown = ", ".join("%s->%.1f" % (k, v[1]) for k, v in sorted(i["onsets"].items(), key=lambda kv: float(kv[0])))
    print("%-18s %-18s %-8d %s" % (key, i["file"][:16], i["frames"], shown))

pairs = [
    ("base same binary, run1 vs run2", "base-plain-run1", "base-plain-run2"),
    ("warp same binary, run1 vs run2", "warp-plain-run1", "warp-plain-run2"),
    ("BASE vs WARP, plain project", "base-plain-run1", "warp-plain-run1"),
    ("BASE vs WARP, plain project (run2)", "base-plain-run2", "warp-plain-run2"),
    ("warp binary: warped vs plain", "warp-warped", "warp-plain-run1"),
    ("BASE binary: warped vs plain", "base-warped", "base-plain-run1"),
]
spread = {}
print()
print("%-42s %-11s %-12s %s" % ("pair (best-aligned)", "differing", "max |delta|", "shift"))
for label, a, b in pairs:
    s, differing, worst = best_alignment(info[a]["samples"], info[b]["samples"])
    spread[label] = (s, differing, worst)
    print("%-42s %-11d %-12.3e %d" % (label, differing, worst, s))

def onset_times(measured, digits=3):
    """Onset positions only: the measured LEVEL moves with the renderer's own
    jitter, and comparing it would make an onset table flaky."""
    return {label: round(hit, digits) for label, (hit, _level) in measured.items()}

verdicts = []

def verdict(name, ok, detail):
    verdicts.append(bool(ok))
    print("%-62s %s  (%s)" % (name, "PASS" if ok else "FAIL", detail))

print()
frames = {key: info[key]["frames"] for key, _ in files}
verdict("1. all six renders complete, same song length",
        len(set(frames.values())) == 1 and all(f > 0 for f in frames.values()),
        "frames %s" % sorted(set(frames.values())))

floor = max(spread["base same binary, run1 vs run2"][1],
            spread["warp same binary, run1 vs run2"][1])
tolerance = max(2 * floor, floor + 512)
verdict("2. run-to-run floor measured and used as the tolerance",
        True,
        "same-binary differing samples base=%d warp=%d -> tolerance %d of %d"
        % (spread["base same binary, run1 vs run2"][1],
           spread["warp same binary, run1 vs run2"][1], tolerance, info["base-plain-run1"]["frames"] * 2))

# 3. BEHAVIOUR PRESERVATION, the measured-spread form: the two binaries agree on
#    a project with no warp to within the floor this run measured, and their
#    transient tables are identical. Byte equality is reported when it holds (it
#    did in the recorded run) but is never the assertion - this tree's renderer
#    is not bit-reproducible.
agree = all(spread[l][1] <= tolerance
            for l in ("BASE vs WARP, plain project", "BASE vs WARP, plain project (run2)"))
same_bytes = info["base-plain-run1"]["file"] == info["warp-plain-run1"]["file"]
verdict("3. no warp: BASE == WARP within the measured floor", agree,
        "differing %d and %d (tolerance %d); identical bytes in this run: %s"
        % (spread["BASE vs WARP, plain project"][1],
           spread["BASE vs WARP, plain project (run2)"][1], tolerance, same_bytes))
verdict("4. no warp: identical burst onsets",
        onset_times(info["base-plain-run1"]["onsets"]) == onset_times(info["warp-plain-run1"]["onsets"]),
        "base %s / warp %s" % (onset_times(info["base-plain-run1"]["onsets"]),
                               onset_times(info["warp-plain-run1"]["onsets"])))

# 5. SENSITIVITY CONTROL: the comparator can see a difference when there is one.
verdict("5. sensitivity: warped project differs beyond the floor",
        spread["warp binary: warped vs plain"][1] > tolerance,
        "differing %d (tolerance %d)" % (spread["warp binary: warped vs plain"][1], tolerance))

# 6. THE MEASUREMENT. The markers declare 2x, so the source's transients come out
#    at half their natural time and the clip's audio ends at 2 s, not 4 s.
expected_warped = {"0.00": 0.0, "0.50": 0.5, "1.00": 1.0, "1.50": 1.5}
expected_plain = {"0.00": 0.0, "1.00": 1.0, "2.00": 2.0, "3.00": 3.0}

def close(measured, expected, tol=0.02):
    for label, want in expected.items():
        if label not in measured:
            return False, "no onset at %s" % label
        if abs(measured[label][0] - want) > tol:
            return False, "onset at %s measured %.3f, expected %.3f" % (label, measured[label][0], want)
    return True, "onsets %s" % ", ".join("%s->%.3f" % (k, measured[k][0]) for k in sorted(measured, key=float))

ok, detail = close(info["warp-plain-run1"]["onsets"], expected_plain)
verdict("6. no warp: transients at 0/1/2/3 s (natural rate)", ok, detail)
ok, detail = close(info["warp-warped"]["onsets"], expected_warped)
verdict("7. WARPED: transients at 0/0.5/1.0/1.5 s - exactly 2x", ok, detail)

# 8. The window's timeline span, not its frame count, is the clip's audio length:
#    2 s of audio here, so the render is silent from 2 s on while the unwarped
#    render still has its 4 s of bursts.
verdict("8. warped render is silent after its 2 s window span",
        info["warp-warped"]["tail"] < -80.0 and info["warp-plain-run1"]["tail"] > -80.0,
        "warped 2-6 s %.1f dB, plain 2-6 s %.1f dB"
        % (info["warp-warped"]["tail"], info["warp-plain-run1"]["tail"]))

# 9. The pre-#597 binary ignores <warp> entirely: it plays the warped project
#    exactly as the plain one, which is why markers were invisible before.
verdict("9. BASE binary ignores <warp> (renders the warped project unwarped)",
        spread["BASE binary: warped vs plain"][1] <= tolerance
        and onset_times(info["base-warped"]["onsets"]) == onset_times(info["base-plain-run1"]["onsets"]),
        "differing %d (tolerance %d), onsets %s, identical bytes: %s"
        % (spread["BASE binary: warped vs plain"][1], tolerance,
           onset_times(info["base-warped"]["onsets"]),
           info["base-warped"]["file"] == info["base-plain-run1"]["file"]))

print()
sys.exit(0 if all(verdicts) else 1)
PY
VERDICT=$?
echo
echo "render-proof verdict exit=$VERDICT (0 = every verdict held)"
exit $VERDICT
